# Generated by Django 2.1.10 on 2020-07-02 14:53

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('organization_name', models.CharField(default='', max_length=128)),
                ('address1', models.CharField(default='', max_length=128)),
                ('address2', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='', max_length=128)),
                ('country', models.CharField(default='', max_length=128)),
                ('office_phone', models.CharField(default='', max_length=128)),
                ('cell_phone', models.CharField(default='', max_length=128)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/%d/')),
                ('organization_image', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/%d/')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='partner_description', to='cms.Placeholder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
