# Generated by Django 2.1.10 on 2020-07-04 11:17

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('users', '0003_auto_20191112_2215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20200702_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('full_bio', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_bio', slotname='partner_full_bio', to='cms.Placeholder')),
                ('institution', models.ManyToManyField(blank=True, null=True, related_name='institution_instructors', to='users.Institution')),
                ('short_bio', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_bio', slotname='partner_short_bio', to='cms.Placeholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('title', models.CharField(default='', max_length=128)),
                ('publisher', models.CharField(default='', max_length=128)),
                ('year', models.SmallIntegerField(default='2020')),
                ('citation', models.CharField(default='', max_length=256)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='partners.Instructors')),
            ],
        ),
    ]
