# Generated by Django 2.1.10 on 2020-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_instructors_publications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructors',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-year', 'order']},
        ),
        migrations.AlterField(
            model_name='instructors',
            name='order',
            field=models.IntegerField(blank=True, default=10000),
        ),
    ]
