# Generated by Django 2.1.10 on 2020-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20200705_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
