# Generated by Django 2.1.10 on 2020-07-07 18:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('partners', '0005_auto_20200707_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
