# Generated by Django 2.1.10 on 2020-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_instructors_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='institution_instructors', to='users.Institution'),
        ),
    ]
