# Generated by Django 3.1.13 on 2024-08-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nces', '0003_debug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['district_dim'], 'verbose_name': 'fact', 'verbose_name_plural': 'factss'},
        ),
    ]
