# Generated by Django 3.1.13 on 2023-10-25 09:06

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_code', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('clusters', models.JSONField(null=True)),
                ('reduced_clusters', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'gendim',
                'verbose_name_plural': 'gendims',
                'ordering': ['gene_code'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('person_code', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('age_at_cdna', models.SmallIntegerField(blank=True, null=True)),
                ('set_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactNormalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('gene_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_dim_fact_normalized', to='mm.genedim')),
                ('person_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_dim_fact_normalized', to='mm.persondim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('gene_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_dim_fact', to='mm.genedim')),
                ('person_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_dim_fact', to='mm.persondim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
