# Generated by Django 3.1.13 on 2024-01-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20240101_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genedim',
            old_name='country_group_dim',
            new_name='gene_group_dim',
        ),
    ]
