# Generated by Django 3.1.13 on 2024-05-29 08:16

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('cell_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_host', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_day_and_time', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch.branches')),
            ],
            options={
                'verbose_name': 'cell',
                'verbose_name_plural': 'cells',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='members', serialize=False, to='auth.user')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member_type', models.SmallIntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.BooleanField(blank=True, default=True, null=True)),
                ('year_of_marriage', models.CharField(blank=True, max_length=20, null=True)),
                ('has_children', models.BooleanField(blank=True, default=True, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('occupation', models.CharField(blank=True, max_length=128, null=True)),
                ('contact1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact2', models.CharField(blank=True, max_length=50, null=True)),
                ('new_convert', models.BooleanField(blank=True, default=False, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch.branches')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch.cells')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch.departments')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ['-created'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch.branches')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_members', to='ch.members')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cells',
            name='cell_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_members', to='ch.members'),
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches_members', to='ch.members'),
        ),
        migrations.CreateModel(
            name='BranchDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_departments_branch', to='ch.branches')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_departments_department', to='ch.departments')),
                ('department_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_members', to='ch.members')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
