# Generated by Django 3.1.13 on 2024-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0002_chweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
