# Generated by Django 3.1.13 on 2024-06-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0003_members_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='cell_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_host_members', to='ch.members'),
        ),
        migrations.AlterField(
            model_name='cells',
            name='cell_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_leader_members', to='ch.members'),
        ),
    ]
