# Generated by Django 3.1.13 on 2024-06-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0004_auto_20240603_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdepartments',
            name='department_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_members', to='ch.members'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_members', to='ch.members'),
        ),
        migrations.AlterField(
            model_name='cells',
            name='cell_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_host_members', to='ch.members'),
        ),
        migrations.AlterField(
            model_name='cells',
            name='cell_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_leader_members', to='ch.members'),
        ),
        migrations.AlterField(
            model_name='members',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ch.branches'),
        ),
        migrations.AlterField(
            model_name='members',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ch.cells'),
        ),
        migrations.AlterField(
            model_name='members',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ch.departments'),
        ),
    ]
