# Generated by Django 3.1.13 on 2024-06-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0006_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_branches', to='ch.branches'),
        ),
        migrations.AlterField(
            model_name='children',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_members', to='ch.members'),
        ),
    ]
