# Generated by Django 3.1.13 on 2022-12-05 00:57

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimeDim',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('measure_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('measure_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_world_Bank_fact', to='potential.measuregroupdim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=16, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_world_Bank_fact', to='potential.countrydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_world_Bank_fact', to='potential.measuredim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_world_Bank_fact', to='potential.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
