# Generated by Django 3.1.13 on 2022-12-05 01:20

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0002_countrydim_fact_measuredim_measuregroupdim_timedim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinMaxCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=16, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=16, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_min_max_cut', to='potential.measuredim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_min_max_cut', to='potential.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
