# Generated by Django 3.1.13 on 2023-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0003_minmaxcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredim',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
