# Generated by Django 3.1.13 on 2022-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
