# Generated by Django 3.1.13 on 2022-05-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20220508_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='AccountingWeb',
        ),
    ]
