# Generated by Django 3.1.13 on 2022-05-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20220508_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='accounting_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_students', to='accounting.accountingweb'),
        ),
    ]
