# Generated by Django 3.1.13 on 2022-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_students_accounting_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
