# Generated by Django 3.1.13 on 2022-05-30 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
