# Generated by Django 3.1.13 on 2022-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_payments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
