# Generated by Django 3.1.13 on 2022-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
