# Generated by Django 3.1.13 on 2022-06-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_students_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
