# Generated by Django 3.1.13 on 2022-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_students_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
