# Generated by Django 3.1.13 on 2022-08-20 14:47

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_payments_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_expenses', to='accounting.accountingweb')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
