# Generated by Django 3.1.13 on 2022-08-23 14:03

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_location', to='accounting.accountingweb')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimeDim',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('quarter', models.PositiveSmallIntegerField(default=0)),
                ('month', models.PositiveSmallIntegerField(default=0)),
                ('day', models.PositiveSmallIntegerField(default=0)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_time_dim', to='accounting.accountingweb')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_time_dim', to='accounting.locations')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_trial_balance', to='accounting.accountingweb')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_trial_balance', to='accounting.locations')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_timedim', to='accounting.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralLedgers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_general_ledger', to='accounting.accountingweb')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_general_ledger', to='accounting.locations')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralLedgerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('accounting_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_general_ledger_detail', to='accounting.accountingweb')),
                ('generalledger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_detail', to='accounting.locations')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_general_ledger_detail', to='accounting.locations')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
