# Generated by Django 3.1.13 on 2022-08-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_generalledgerdetail_generalledgers_locations_timedim_trialbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='level',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
