# Generated by Django 3.1.13 on 2022-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_trialbalance_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedim',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
