# Generated by Django 3.1.13 on 2022-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20220825_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
