# Generated by Django 3.1.13 on 2022-08-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20220825_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedim',
            name='accounting_web',
        ),
        migrations.RemoveField(
            model_name='timedim',
            name='location',
        ),
    ]
