# Generated by Django 3.1.13 on 2022-08-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20220826_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgers',
            name='created',
        ),
        migrations.AddField(
            model_name='generalledgers',
            name='time_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_timedim', to='accounting.timedim'),
        ),
    ]
