# Generated by Django 3.1.13 on 2022-08-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20220828_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgerdetail',
            name='generalledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gl_general_ledger_detail', to='accounting.generalledgers'),
        ),
    ]
