# Generated by Django 3.1.13 on 2022-08-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20220829_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgerdetail',
            name='location',
        ),
    ]
