# Generated by Django 3.1.13 on 2022-09-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_remove_generalledgerdetail_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledgerdetail',
            options={'ordering': ['generalledger', 'account'], 'verbose_name': 'GeneralLedgerDetail', 'verbose_name_plural': 'GeneralLedgerDetail'},
        ),
    ]
