# Generated by Django 3.0.10 on 2021-02-06 18:37

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('town_name', models.CharField(blank=True, default='', max_length=100)),
                ('mayor', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.NullBooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Please supply the course slug.', max_length=128, verbose_name='slug')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_image', to=settings.FILER_IMAGE_MODEL)),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_logo', to=settings.FILER_IMAGE_MODEL)),
                ('staff_members', models.ManyToManyField(default=1, related_name='staff_towns', to=settings.AUTH_USER_MODEL)),
                ('town_clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clerks_towns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'town',
                'verbose_name_plural': 'towns',
                'ordering': ['order'],
            },
        ),
    ]
