# Generated by Django 3.0.10 on 2021-02-06 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugandatowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='staff_towns', to=settings.AUTH_USER_MODEL),
        ),
    ]
