# Generated by Django 3.0.10 on 2021-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0002_auto_20210206_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='town_clerk',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
