# Generated by Django 3.0.10 on 2021-02-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0003_auto_20210206_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='staff_members',
        ),
    ]
