# Generated by Django 3.0.10 on 2021-02-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0004_remove_towns_staff_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='towns',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='towns',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='towns',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
