# Generated by Django 3.0.10 on 2021-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0005_auto_20210207_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='bottom_info_color',
            field=models.CharField(blank=True, default='blue', max_length=100),
        ),
    ]
