# Generated by Django 3.0.10 on 2021-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0006_towns_bottom_info_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='media_ticker',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
