# Generated by Django 3.0.10 on 2021-02-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ugandatowns', '0007_towns_media_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='bottom_info_color',
            field=models.CharField(blank=True, default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='towns',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='towns',
            name='mayor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='towns',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='towns',
            name='town_clerk',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='towns',
            name='town_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='TownStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.IntegerField(choices=[(0, 'Mayor'), (1, 'Town Clerk'), (2, 'Municipal Speaker'), (5, 'Accountant'), (10, 'Other')], default=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_staff_image', to=settings.FILER_IMAGE_MODEL)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_staffs', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'town_staff',
                'verbose_name_plural': 'town_staffs',
            },
        ),
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'received_message',
                'verbose_name_plural': 'received_messages',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementsNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_type', models.IntegerField(choices=[(1, 'News'), (2, 'Announcement')], default=1)),
                ('message_title', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_news_image', to=settings.FILER_IMAGE_MODEL)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_news', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
            },
        ),
    ]
