# Generated by Django 3.0.10 on 2021-02-11 15:52

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('ugandatowns', '0009_auto_20210211_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.NullBooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Please supply the project slug.', max_length=128, verbose_name='slug')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_directors', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'ordering': ['order'],
            },
        ),
    ]
