# Generated by Django 3.0.10 on 2021-02-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0012_newannouncements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementsNews',
        ),
    ]
