# Generated by Django 3.0.10 on 2021-02-15 06:23

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('ugandatowns', '0014_tenders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('tourism_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.NullBooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Please supply the tourism slug.', max_length=128, verbose_name='slug')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_tourism', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'tourism',
                'verbose_name_plural': 'many tourism',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('career_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.NullBooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Please supply the career slug.', max_length=128, verbose_name='slug')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_careers', to='ugandatowns.Towns')),
            ],
            options={
                'verbose_name': 'career',
                'verbose_name_plural': 'careers',
                'ordering': ['order'],
            },
        ),
    ]
