# Generated by Django 3.0.10 on 2021-02-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0015_careers_tourism'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourism',
            options={'ordering': ['order'], 'verbose_name': 'tourism', 'verbose_name_plural': 'tourism'},
        ),
    ]
