# Generated by Django 3.0.10 on 2021-02-23 21:25

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('ugandatowns', '0016_auto_20210221_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='map',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_map', slotname='map', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_description', slotname='description', to='cms.Placeholder'),
        ),
    ]
