# Generated by Django 3.0.10 on 2021-02-23 22:48

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('ugandatowns', '0017_auto_20210223_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='map',
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder')),
                ('town', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='town_contact_us', to='ugandatowns.Towns')),
            ],
        ),
    ]
