# Generated by Django 3.0.10 on 2021-03-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0018_auto_20210224_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
