# Generated by Django 3.0.10 on 2021-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0019_auto_20210310_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='towns',
            name='contact_us_email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='towns',
            name='menus_info_color',
            field=models.CharField(blank=True, default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='towns',
            name='bottom_info_color',
            field=models.CharField(blank=True, default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='towns',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
