# Generated by Django 3.0.10 on 2021-04-21 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugandatowns', '0020_auto_20210413_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencing',
            fields=[
                ('conference_number', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.NullBooleanField(default=True)),
                ('tc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['-created_date'],
            },
        ),
    ]
