# Generated by Django 3.0.10 on 2021-05-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0023_auto_20210425_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towns', to='ugandatowns.Countries'),
        ),
    ]
