# Generated by Django 3.0.10 on 2021-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0024_auto_20210511_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='image_bg',
            field=models.ImageField(blank=True, default='fab_hose_africa_web/no_image.png', null=True, upload_to='ugandatowns/countries/'),
        ),
        migrations.AddField(
            model_name='countries',
            name='image_login_in',
            field=models.ImageField(blank=True, default='fab_hose_africa_web/no_image.png', null=True, upload_to='ugandatowns/countries/'),
        ),
        migrations.AddField(
            model_name='countries',
            name='image_login_out',
            field=models.ImageField(blank=True, default='fab_hose_africa_web/no_image.png', null=True, upload_to='ugandatowns/countries/'),
        ),
    ]
