# Generated by Django 3.1.13 on 2021-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugandatowns', '0025_auto_20210513_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conferencing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newannouncements',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='towns',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
