# pull official base image
FROM python:3.8.5
# -alpine
MAINTAINER AcademyCity.org

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install dependencies
RUN pip install --upgrade pip
#RUN pip install flake8

# install psycopg2 dependencies
#RUN apk add --update --no-cache --virtual .tmp
 #\
# gcc libc-dev linux-headers
    #&& apk add postgresql-dev \
    # python3-dev musl-dev
    # && apk add jpeg-dev zlib-dev libjpeg libffi-dev \
    #&& pip install Pillow=7.0.2 \
    #&& pip install psycopg2-binary==2.8.6
RUN pip install Pillow==7.2.0 psycopg2-binary==2.8.6

COPY requirements.txt /usr/src/app/
COPY manageacademycity.py /usr/src/app/

COPY academycity-daphne.service /etc/systemd/system/

# RUN pip install djangocms-installer
# RUN pip install djangocms-bootstrap4

# RUN flake8 --ignore=E501,F401 .

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/src/app

# RUN apk del .tmp
COPY . /usr/src/app



# install cmake
# RUN apt-get update \
#   && apt-get -y install build-essential \
#   && apt-get install -y wget \
#   && rm -rf /var/lib/apt/lists/* \
#   && wget https://github.com/Kitware/CMake/releases/download/v3.24.1/cmake-3.24.1-Linux-x86_64.sh \
#       -q -O /tmp/cmake-install.sh \
#       && chmod u+x /tmp/cmake-install.sh \
#       && mkdir /opt/cmake-3.24.1 \
#       && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-3.24.1 \
#       && rm /tmp/cmake-install.sh \
#       && ln -s /opt/cmake-3.24.1/bin/* /usr/local/bin

# install dlib
# RUN git clone https://github.com/davisking/dlib.git dlib
# WORKDIR /usr/src/app/dlib
# RUN python3 setup.py install
# RUN pip install
# WORKDIR /usr/src/app
