# Generated by Django 3.1.13 on 2021-11-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppwivesWeb',
            new_name='ApewivesWeb',
        ),
    ]
