# Generated by Django 3.1.13 on 2021-11-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0002_auto_20211109_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='main_page_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='membership_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='membership_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='membership_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='ownership_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='roadmap_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='specs_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='specs_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='specs_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='text_main_page_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='text_second_page_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='text_second_page_title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.CreateModel(
            name='TitleSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(blank=True, default='', max_length=512)),
                ('apewives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titleslides', to='apewives.apewivesweb')),
            ],
            options={
                'verbose_name': 'title slide',
                'verbose_name_plural': 'title slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/team')),
                ('apewives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='apewives.apewivesweb')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlidingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home')),
                ('apewives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliding_images', to='apewives.apewivesweb')),
            ],
            options={
                'verbose_name': 'sliding image',
                'verbose_name_plural': 'sliding images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(blank=True, default='', max_length=512)),
                ('link', models.CharField(blank=True, default='', max_length=100)),
                ('apewives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='apewives.apewivesweb')),
            ],
            options={
                'verbose_name': 'roadmap',
                'verbose_name_plural': 'roadmaps',
                'ordering': ['order'],
            },
        ),
    ]
