# Generated by Django 3.1.13 on 2021-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0004_apewivesweb_main_page_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='community_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='community_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
