# Generated by Django 3.1.13 on 2021-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0005_auto_20211110_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='buy_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='buy_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
