# Generated by Django 3.1.13 on 2021-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0006_auto_20211110_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='buy_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
    ]
