# Generated by Django 3.1.13 on 2021-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0007_apewivesweb_buy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='specs_text_2',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
