# Generated by Django 3.1.13 on 2021-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0010_auto_20211110_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='member_tool_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='member_tool_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
