# Generated by Django 3.1.13 on 2021-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0011_auto_20211110_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='member_rarity_tools',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
