# Generated by Django 3.1.13 on 2021-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0012_apewivesweb_member_rarity_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='team_text',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='team_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
