# Generated by Django 3.1.13 on 2021-11-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0013_auto_20211110_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='data_id_1',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='data_id_2',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='team_description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='team',
            name='team_header',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
