# Generated by Django 3.1.13 on 2021-11-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0016_auto_20211111_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
