# Generated by Django 3.1.13 on 2021-11-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0017_auto_20211111_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_1',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_2',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_text_3',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_1',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_2',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_3',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_4',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_5',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='read_more_about_text_6',
            field=models.CharField(blank=True, default='', max_length=1050),
        ),
    ]
