# Generated by Django 3.1.13 on 2021-11-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0019_auto_20211111_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='main_page_discord_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='main_page_discord_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='main_page_twitter_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='main_page_twitter_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
