# Generated by Django 3.1.13 on 2021-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0020_auto_20211111_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='community_discord_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='community_twitter_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
    ]
