# Generated by Django 3.1.13 on 2021-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0021_auto_20211111_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='buy_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
