# Generated by Django 3.1.13 on 2021-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0022_apewivesweb_buy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='link_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='roadmap_data_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='roadmap_timeline_item_point',
            field=models.IntegerField(default=0),
        ),
    ]
