# Generated by Django 3.1.13 on 2021-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0024_auto_20211111_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_1',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_2',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_3',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_1',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_2',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_3',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_4',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_5',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_text_6',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='read_more_about_title',
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='about_text_bottom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='about_text_top',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
