# Generated by Django 3.1.13 on 2021-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0025_auto_20211111_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='logo_image_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
