# Generated by Django 3.1.13 on 2021-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0026_apewivesweb_logo_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='instagram_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='instagram_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='youtube_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home'),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='youtube_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
