# Generated by Django 3.1.13 on 2021-11-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0027_auto_20211111_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='member_rarity_tools_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
