# Generated by Django 3.1.13 on 2021-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0028_apewivesweb_member_rarity_tools_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='specs_text',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='specs_text_2',
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='specs_text_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
