# Generated by Django 3.1.13 on 2021-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0031_auto_20211112_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='buy_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/buy_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_discord_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_twitter_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='instagram_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_discord_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/main_page_image'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_logo_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/main_page_image'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_twitter_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='membership_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/membership_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='ownership_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/ownership_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='roadmap_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/roadmap_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='specs_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/specs_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='youtube_image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='slidingimages',
            name='image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/home/sliding_images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='apewives_web/home/no_image.png', upload_to='apewives_web/team/team_images'),
        ),
    ]
