# Generated by Django 3.1.13 on 2021-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0032_auto_20211114_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_discord_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_twitter_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_discord_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/main_page_image'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_logo_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/main_page_image'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_twitter_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='specs_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/specs_images'),
        ),
    ]
