# Generated by Django 3.1.13 on 2021-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0033_auto_20211116_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='about_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='buy_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/buy_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='buy_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='buy_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='buy_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='community_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='footer_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='footer_title_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='footer_title_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='instagram_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='instagram_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='logo_image_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_discord_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='main_page_twitter_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='member_rarity_tools',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='member_rarity_tools_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='member_tool_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='member_tool_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='membership_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/membership_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='membership_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='membership_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='ownership_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/ownership_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='ownership_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='roadmap_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/roadmap_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='roadmap_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='roadmap_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='specs_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='team_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='team_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='text_main_page_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='text_second_page_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='text_second_page_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='youtube_image',
            field=models.ImageField(default='no_image.png', upload_to='apewives_web/home/social_media_images'),
        ),
        migrations.AlterField(
            model_name='apewivesweb',
            name='youtube_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
