# Generated by Django 3.1.13 on 2021-11-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0034_auto_20211116_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_bottom',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_top',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='buy_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_discord_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_twitter_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='contract_address_text_paragraph',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='instagram_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='main_page_discord_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='main_page_logo_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='main_page_twitter_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='main_page_twitter_link',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='membership_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='ownership_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='ownership_text_paragraph',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='roadmap_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='specs_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='specs_text_paragraph',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='text_main_page_title',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='youtube_image',
        ),
    ]
