# Generated by Django 3.1.13 on 2021-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0036_auto_20211117_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='text_second_page_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
