# Generated by Django 3.1.13 on 2021-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0037_auto_20211126_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='apewivesweb',
            name='apes_out_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apewivesweb',
            name='apes_out_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
