# Generated by Django 3.1.13 on 2021-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0038_auto_20211126_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apewivesweb',
            name='team_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
