# Generated by Django 3.1.13 on 2021-11-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0039_auto_20211126_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='buy_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='buy_link',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='buy_text',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='buy_title',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_discord_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_text',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_title',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='community_twitter_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='member_rarity_tools',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='member_rarity_tools_link',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='member_tool_text',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='member_tool_title',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='membership_image',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='membership_text',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='membership_title',
        ),
    ]
