# Generated by Django 3.1.13 on 2021-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0040_auto_20211126_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='roadmap_text',
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titleslides',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
