# Generated by Django 3.1.13 on 2021-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0041_auto_20211126_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='roadmap_timeline_item_point',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
