# Generated by Django 3.1.13 on 2021-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0042_auto_20211126_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='roadmap_timeline_item_point',
            field=models.IntegerField(default=10),
        ),
    ]
