# Generated by Django 3.1.13 on 2021-11-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0043_auto_20211126_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_bottom',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_text_top',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='contract_address_text_paragraph',
        ),
    ]
