# Generated by Django 3.1.13 on 2021-11-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0044_auto_20211126_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='logo_image_link',
        ),
    ]
