# Generated by Django 3.1.13 on 2021-11-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apewives', '0045_remove_apewivesweb_logo_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apewivesweb',
            name='footer_title_1',
        ),
        migrations.RemoveField(
            model_name='apewivesweb',
            name='footer_title_2',
        ),
    ]
