# Generated by Django 2.1.10 on 2020-07-13 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Right', models.CharField(max_length=1)),
                ('Ticker', models.CharField(max_length=10)),
                ('OrderDate', models.DateTimeField(auto_now_add=True, verbose_name='date ordered')),
                ('ContractDate', models.CharField(max_length=8)),
                ('LeftStrike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderAskPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderBidPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderAveragePrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderClose', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderBidSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftOrderAskSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftActualPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('LeftActualUndPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidStrike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderAskPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderBidPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderAveragePrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderClose', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderBidSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidOrderAskSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidActualPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('MidActualUndPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightStrike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderAskPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderBidPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderAveragePrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderClose', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderBidSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightOrderAskSize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightActualPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('RightActualUndPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('StrategyPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('TransactionCost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
            ],
        ),
    ]
