# Generated by Django 3.0.10 on 2021-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0003_contact_home_receivedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_us_email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='information_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_message_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
