# Generated by Django 3.0.10 on 2021-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0004_auto_20210510_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandweb',
            name='company_short_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bizlandweb',
            name='youtube_video_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
