# Generated by Django 3.0.10 on 2021-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0005_auto_20210510_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandweb',
            name='link_to_about_us',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
