# Generated by Django 3.0.10 on 2021-05-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0008_auto_20210510_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('bizland_web', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='bizland.BizlandWeb')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_categories', to='bizland.Portfolio')),
            ],
            options={
                'verbose_name': 'portfolio category',
                'verbose_name_plural': 'portfolio categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='fab_hose_africa_web/no_image.png', null=True, upload_to='bizland/portfolio/')),
                ('portfolio_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='bizland.PortfolioCategory')),
            ],
            options={
                'verbose_name': 'portfolio item',
                'verbose_name_plural': 'portfolio items',
            },
        ),
    ]
