# Generated by Django 3.0.10 on 2021-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0009_portfolio_portfoliocategory_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
