# Generated by Django 3.0.10 on 2021-05-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0010_portfoliocategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bizland_web',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='bizland.BizlandWeb'),
        ),
    ]
