# Generated by Django 3.1.13 on 2022-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0002_auto_20221114_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldbankfact',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
