# Generated by Django 3.1.13 on 2023-01-12 15:28

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0005_measuredim_measure_group_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_university', to='avi.countrydim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='worldbankfact',
            name='measure_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_world_Bank_fact', to='avi.measuredim'),
        ),
        migrations.CreateModel(
            name='UniversityRankFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_university_rank_fact', to='avi.countrydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_university_rank_fact', to='avi.measuredim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_university_rank_fact', to='avi.timedim')),
                ('university_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='university_dim_university_rank_fact', to='avi.universitydim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
