# Generated by Django 3.1.13 on 2023-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0006_auto_20230112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydim',
            name='country_cc',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
