# Generated by Django 3.1.13 on 2023-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0008_minmaxcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minmaxcut',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='minmaxcut',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=18, null=True),
        ),
    ]
