# Generated by Django 3.1.13 on 2023-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0009_auto_20230129_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minmaxcut',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='minmaxcut',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True),
        ),
    ]
