# Generated by Django 3.1.13 on 2023-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0010_auto_20230318_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredim',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
