# Generated by Django 2.1.10 on 2020-07-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='target_ct',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='target_id',
            new_name='object_id',
        ),
    ]
