# Generated by Django 3.0.10 on 2021-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoForSamuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
            ],
        ),
    ]
