# Generated by Django 3.0.10 on 2021-07-11 14:06

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('education', '0025_program_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionweb',
            old_name='github_domain_name',
            new_name='facebook_link',
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institutionweb',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_course_description', slotname='description', to='cms.Placeholder'),
        ),
    ]
