# Generated by Django 3.0.10 on 2021-07-15 07:41

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('education', '0026_auto_20210711_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_description', slotname='description', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_description', slotname='description', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_description', slotname='description', to='cms.Placeholder'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Programs/')),
                ('service_title', models.CharField(max_length=100, null=True)),
                ('service_description', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_description', slotname='description', to='cms.Placeholder')),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='education.InstitutionWeb')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
