# Generated by Django 3.0.10 on 2021-07-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20210709_0956'),
        ('education', '0029_auto_20210718_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='course_courses', to='courses.Course'),
        ),
    ]
