# Generated by Django 3.0.10 on 2021-07-2  16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_receivedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='programs_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
