# Generated by Django 3.0.10 on 2021-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0036_institutionweb_new_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='person_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
