# Generated by Django 3.0.10 on 2021-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0043_auto_20210731_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaltopic',
            name='is_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='is_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
