# Generated by Django 3.0.10 on 2021-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0044_auto_20210807_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='gradient_color_1',
            field=models.CharField(default='#969696', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='gradient_color_2',
            field=models.CharField(default='#dfdfdf', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='name_gradient_deg',
            field=models.IntegerField(blank=True, default=285),
        ),
        migrations.AddField(
            model_name='new',
            name='name_text_color',
            field=models.CharField(default='#090909', max_length=10, null=True),
        ),
    ]
