# Generated by Django 3.1.13 on 2023-08-29 11:50

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avic', '0003_countrydim_country_group_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OutputFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_output_fact', to='avic.countrydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_output_fact', to='avic.measuredim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_output_fact', to='avic.rangedim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_output_fact', to='avic.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
