# Generated by Django 3.1.13 on 2023-09-05 13:57

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avic', '0004_outputfact_rangedim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelImpFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_relimp_fact', to='avic.measuredim')),
                ('measure_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_group_dim_relimp_fact', to='avic.measuregroupdim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_relimp_fact', to='avic.rangedim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_relimp_fact', to='avic.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
