# Generated by Django 3.1.13 on 2023-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avic', '0005_relimpfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputfact',
            name='range_name',
            field=models.CharField(blank=True, default='min', max_length=10, null=True),
        ),
    ]
