# Generated by Django 2.1.10 on 2020-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'General'), (5, 'Data Science'), (10, 'Finance'), (15, 'Business Intelligence'), (20, 'Machine Learning'), (25, 'Business Simulation'), (30, 'Partners')], default=0),
        ),
    ]
