# Generated by Django 3.0.10 on 2021-07-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210707_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioweb',
            options={'ordering': ['order'], 'verbose_name': 'portfolioweb', 'verbose_name_plural': 'portfoliowebs'},
        ),
    ]
