# Generated by Django 3.0.10 on 2021-07-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210711_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioweb',
            name='welcome_phrase1',
        ),
        migrations.RemoveField(
            model_name='portfolioweb',
            name='welcome_phrase2',
        ),
    ]
