# Generated by Django 3.1.13 on 2023-12-2  11:15

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('entity_serial', models.PositiveSmallIntegerField(default=0)),
                ('entity_race', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('measure_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RangeDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelImpFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_relimp_fact', to='arthur.measuredim')),
                ('measure_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_group_dim_relimp_fact', to='arthur.measuregroupdim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_relimp_fact', to='arthur.rangedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OutputFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(blank=True, default='min', max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('entity_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_dim_output_fact', to='arthur.entitydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_output_fact', to='arthur.measuredim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_output_fact', to='arthur.rangedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MinMaxCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_min_max_cut', to='arthur.measuredim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='measuredim',
            name='measure_group_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_group_measures', to='arthur.measuregroupdim'),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('entity_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_dim_fact', to='arthur.entitydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fact_measures', to='arthur.measuredim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
