# Generated by Django 2.1.10 on 2020-04-13 09:23

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiontranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questiontranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='question_text', to='cms.Placeholder'),
        ),
        migrations.DeleteModel(
            name='QuestionTranslation',
        ),
    ]
