# Generated by Django 2.1.10 on 2020-04-13 16:42

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('elearning', '0002_auto_20200413_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answertranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answertranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='answer_text', to='cms.Placeholder'),
        ),
        migrations.DeleteModel(
            name='AnswerTranslation',
        ),
    ]
