# Generated by Django 3.1.11 on 2021-07-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_course_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreNewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_detail/')),
                ('news_type', models.CharField(max_length=100, null=True)),
                ('news_type_description', models.CharField(max_length=100, null=True)),
                ('news_title', models.CharField(max_length=100, null=True)),
                ('news_description', models.CharField(max_length=500, null=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='more_news_details', to='education.institutionweb')),
            ],
            options={
                'verbose_name': 'more_news_detail',
                'verbose_name_plural': 'more_news_details',
                'ordering': ['order'],
            },
        ),
    ]
