# Generated by Django 3.0.10 on 2021-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_institutionweb_programs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='courses_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
