# Generated by Django 3.0.10 on 2021-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0037_institutionweb_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='person_phrase_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
