# Generated by Django 3.0.10 on 2021-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0039_institutionweb_other_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='services',
            name='gradient_color_1',
            field=models.CharField(default='#969696', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='gradient_color_2',
            field=models.CharField(default='#dfdfdf', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_gradient_deg',
            field=models.IntegerField(blank=True, default=285),
        ),
        migrations.AddField(
            model_name='services',
            name='name_text_color',
            field=models.CharField(default='#090909', max_length=10, null=True),
        ),
    ]
