# Generated by Django 3.0.10 on 2021-07-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0041_auto_20210723_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cv_number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_type',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
