# Generated by Django 3.0.10 on 2021-08-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0046_auto_20210810_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaltopic',
            name='is_link',
        ),
        migrations.RemoveField(
            model_name='new',
            name='is_link',
        ),
        migrations.AddField(
            model_name='additionaltopic',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
    ]
