# Generated by Django 3.0.10 on 2021-08-11 07:23

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('education', '0047_auto_20210811_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaltopic',
            name='topic_description',
        ),
        migrations.AddField(
            model_name='additionaltopic',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_description', slotname='description', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='additionaltopic',
            name='topic_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
