# Generated by Django 3.0.10 on 2021-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0048_auto_20210811_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
    ]
