# Generated by Django 3.1.13 on 2021-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0050_auto_20211122_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionweb',
            name='subjects_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
