# Generated by Django 2.1.10 on 2019-08-31 01:22

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default='', help_text='Please supply the course slug.', max_length=128, verbose_name='slug')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='courses.Course')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='course_ schedule_description', to='cms.Placeholder')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'course schedule',
                'verbose_name_plural': 'courses schedule',
            },
        ),
        migrations.CreateModel(
            name='CourseScheduleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('active', models.NullBooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default='', help_text='Please supply the course slug.', max_length=128, verbose_name='slug')),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='courses.CourseSchedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course schedule user',
                'verbose_name_plural': 'courses schedule user',
            },
        ),
    ]
