# Generated by Django 2.1.10 on 2019-09-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseschedule_coursescheduleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursescheduleuser',
            name='active',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursescheduleuser',
            name='course_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_course_schedules', to='courses.CourseSchedule'),
        ),
    ]
