# Generated by Django 2.1.10 on 2019-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190911_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
