# Generated by Django 2.1.10 on 2019-09-23 17:56

import academycity.apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=0),
        ),
    ]
