# Generated by Django 2.1.10 on 2019-09-28 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_auto_20190923_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(default=1, related_name='user_instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='instructors',
            field=models.ManyToManyField(default=1, related_name='course_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
