# Generated by Django 2.1.10 on 2019-10-05 00:37

import academycity.apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190929_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=1),
        ),
    ]
