# Generated by Django 2.1.10 on 2019-10-07 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_auto_20191005_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_course_schedule_owns', to=settings.AUTH_USER_MODEL),
        ),
    ]
