# Generated by Django 2.1.10 on 2019-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course_schedule_user_slug',
            field=models.SlugField(default='', help_text='Please supply the course slug.', max_length=128, verbose_name='course_schedule_user_slug'),
        ),
    ]
