# Generated by Django 2.1.10 on 2019-10-18 01:25

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0013_order_braintree_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000000000', max_length=10)),
                ('parent', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'chart_of_account',
                'verbose_name_plural': 'chart_of_accounts',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChartOfAccountsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('account', models.CharField(db_index=True, default='', help_text='Please supply the account name.', max_length=128, verbose_name='account')),
                ('slug', models.SlugField(default='', help_text='Please supply the department slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.ChartOfAccounts')),
            ],
            options={
                'verbose_name': 'chart_of_account Translation',
                'db_table': 'courses_chartofaccounts_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('transaction', models.PositiveIntegerField()),
                ('sub_transaction', models.SmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofa_gls', to='courses.ChartOfAccounts')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_gl_obj', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'general ledger',
                'verbose_name_plural': 'general ledgers',
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofa_tbs', to='courses.ChartOfAccounts')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccountstranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
