# Generated by Django 2.1.10 on 2019-10-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20191018_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.ChartOfAccounts'),
        ),
    ]
