# Generated by Django 2.1.10 on 2019-10-19 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20191018_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='flow_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'flow'), (2, 'cumulative')], default=1),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='for_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='period_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'day'), (2, 'month'), (3, 'year')], default=1),
        ),
    ]
