# Generated by Django 2.1.10 on 2019-10-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20191019_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='updated',
        ),
    ]
