# Generated by Django 2.1.10 on 2019-10-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20191019_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='for_date',
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='pkey_date',
            field=models.IntegerField(default=0),
        ),
    ]
