# Generated by Django 2.1.10 on 2019-10-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20191020_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
