# Generated by Django 2.1.10 on 2019-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20191020_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.SmallIntegerField(default='2'),
        ),
    ]
