# Generated by Django 2.1.10 on 2019-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
