# Generated by Django 2.1.10 on 2019-10-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20191026_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule_teams', to='courses.CourseScheduleTeam'),
        ),
    ]
