# Generated by Django 2.1.10 on 2019-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20191102_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link_app',
            field=models.CharField(blank=True, help_text='Please supply the link_app.', max_length=50, verbose_name='link_app'),
        ),
        migrations.AddField(
            model_name='course',
            name='link_model',
            field=models.CharField(blank=True, help_text='Please supply the link_model.', max_length=50, verbose_name='link_model'),
        ),
    ]
