# Generated by Django 2.1.10 on 2019-11-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20191102_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__in': 'instructors'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_owns', to=settings.AUTH_USER_MODEL),
        ),
    ]
