# Generated by Django 2.1.10 on 2019-11-08 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0035_auto_20191103_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Homework'), (2, 'Assignment')], default=2)),
                ('period_start', models.DateTimeField(auto_now=True)),
                ('period_end', models.DateTimeField(auto_now=True)),
                ('sub_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.SubSection')),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homework',
            },
        ),
        migrations.CreateModel(
            name='AssignmentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.Assignment')),
                ('course_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='courses.CourseSchedule')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment_user',
                'verbose_name_plural': 'assignments_user',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Please supply the team name.', max_length=50, verbose_name='name')),
                ('course_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_teams', to='courses.CourseSchedule')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
    ]
