# Generated by Django 2.1.10 on 2019-11-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_assignment_assignmentuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='courses.Team'),
        ),
    ]
