# Generated by Django 2.1.10 on 2019-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_coursescheduleuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
