# Generated by Django 2.1.10 on 2019-11-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_course_is_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='assignment_method',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Individual'), (2, 'Random')], default=1),
        ),
    ]
