# Generated by Django 2.1.10 on 2019-11-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_courseschedule_assignment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='max_number_of_teams',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='max_students_per_team',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='min_number_of_teams',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='min_students_per_team',
            field=models.IntegerField(default=3),
        ),
    ]
