# Generated by Django 2.1.10 on 2019-11-10 16:30

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('courses', '0040_auto_20191109_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'assignment', 'verbose_name_plural': 'assignments'},
        ),
        migrations.AddField(
            model_name='assignmentuser',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='assignment_user_description', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sub_section',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.SubSection'),
        ),
        migrations.AlterField(
            model_name='assignmentuser',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_assignment_users', to='courses.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentuser',
            name='course_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules_assignment_users', to='courses.CourseSchedule'),
        ),
        migrations.AlterField(
            model_name='assignmentuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
