# Generated by Django 2.1.10 on 2019-11-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20191110_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentuser',
            name='course_schedule',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules_assignments', to='courses.CourseSchedule'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sub_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.SubSection'),
        ),
        migrations.AlterField(
            model_name='assignmentuser',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_users', to='courses.Assignment'),
        ),
    ]
