# Generated by Django 2.1.10 on 2019-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20191110_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='period_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='period_start',
            field=models.DateTimeField(),
        ),
    ]
