# Generated by Django 2.1.10 on 2019-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20191111_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='period_start',
            field=models.DateTimeField(null=True),
        ),
    ]
