# Generated by Django 2.1.10 on 2019-11-16 20:00

import academycity.apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20191116_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentusercontent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='assignmentusercontent',
            name='order',
            field=academycity.apps.core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
