# Generated by Django 2.1.10 on 2019-11-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0046_auto_20191116_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentuser',
            name='owner',
        ),
        migrations.AddField(
            model_name='assignmentuser',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='assignmentuser',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
