# Generated by Django 2.1.10 on 2019-11-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0047_auto_20191117_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='assignmentuser',
            name='object_id',
        ),
        migrations.AddField(
            model_name='assignmentuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentuser',
            name='team_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner_assignments', to='courses.Team'),
        ),
    ]
