# Generated by Django 2.1.10 on 2019-11-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20191117_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
    ]
