# Generated by Django 2.1.10 on 2020-04-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0049_auto_20191118_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('game', 'project')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
