# Generated by Django 2.1.10 on 2020-04-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20200418_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('game', 'project')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='contenttypes.ContentType'),
        ),
    ]
