# Generated by Django 2.1.10 on 2020-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20200510_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.NullBooleanField(default=True),
        ),
    ]
