# Generated by Django 3.0.10 on 2020-11-07 22:27

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_auto_20200831_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccountstranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.ChartOfAccounts'),
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='departmenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Department'),
        ),
        migrations.AlterField(
            model_name='sectiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='subsectiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.SubSection'),
        ),
        migrations.AlterField(
            model_name='syllabustranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Syllabus'),
        ),
    ]
