# Generated by Django 3.0.10 on 2021-01-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_auto_20201108_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['-start_date'], 'verbose_name': 'course schedule', 'verbose_name_plural': 'courses schedule'},
        ),
    ]
