# Generated by Django 3.0.10 on 2021-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_auto_20210108_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleuser',
            name='graduated',
            field=models.NullBooleanField(default=False),
        ),
    ]
