# Generated by Django 3.0.10 on 2021-01-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_coursescheduleuser_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleuser',
            name='certificate_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
