# Generated by Django 3.0.10 on 2021-01-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_coursescheduleuser_certificate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursescheduleuser',
            name='certificate_number',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='certificate_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
