# Generated by Django 3.0.10 on 2021-07-09 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0059_auto_20210112_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='user_instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='instructors',
            field=models.ManyToManyField(related_name='course_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
