# Generated by Django 3.1.13 on 2021-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20210709_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursescheduleuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursescheduleuser',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
