# Generated by Django 3.0.10 on 2021-05-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='BizlandWeb',
        ),
    ]
