# Generated by Django 3.0.10 on 2021-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0006_bizlandweb_link_to_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizlandweb',
            name='background_1',
            field=models.ImageField(blank=True, default='fab_hose_africa_web/no_image.png', null=True, upload_to='bizland/'),
        ),
    ]
