# Generated by Django 3.0.10 on 2021-05-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizland', '0007_bizlandweb_background_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('link_url_name', models.CharField(blank=True, default='', max_length=50)),
                ('bizland_web', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bizland.BizlandWeb')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
