# Generated by Django 3.1.13 on 2024-05-24 11:21

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactNormalizedMinMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('entity_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_dim_fact_normalized_minmax', to='covid.entitydim')),
                ('var_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_dim_fact_normalized_minmax', to='covid.vardim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
