# Generated by Django 3.1.13 on 2024-06-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_factnormalizedminmax_dip_var_dim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factnormalizedminmax',
            old_name='dip_var_dim',
            new_name='dep_var_dim',
        ),
    ]
