# Generated by Django 3.1.13 on 2022-09-13 15:09

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('State', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('team_manager', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='businesssimweb',
            old_name='company_name',
            new_name='group_name',
        ),
        migrations.RemoveField(
            model_name='businesssimweb',
            name='address',
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='number_of_participant',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='number_of_periods',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tb_general_ledger', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='teams',
            name='businesssimm_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesssimm_teams', to='businesssim.businesssimweb'),
        ),
        migrations.CreateModel(
            name='RandDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_period', models.SmallIntegerField(default=1)),
                ('project_name', models.CharField(default='new', max_length=50)),
                ('prime_cost', models.IntegerField(default=100)),
                ('investment', models.IntegerField(default=1000000)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_randds', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RandDProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(blank=True, default='new', max_length=50, null=True)),
                ('value', models.SmallIntegerField(default=20)),
                ('randd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='randd_properties', to='businesssim.randds')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new product', max_length=50)),
                ('created_period', models.SmallIntegerField(default=1)),
                ('abandon_period', models.SmallIntegerField(default=-1)),
                ('randd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='randd_products', to='businesssim.randds')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_products', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('retail_price', models.SmallIntegerField(verbose_name=400)),
                ('planned_production', models.IntegerField(default=10000)),
                ('planned_safety_stock', models.IntegerField(default=1000)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_periods', to='businesssim.products')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('State', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('businesssimm_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesssimm_participants', to='businesssim.businesssimweb')),
                ('institution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution_participants', to='businesssim.institutions')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_participants', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('channel', models.CharField(default='', max_length=25)),
                ('amount', models.IntegerField(default=500000)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_marketing', to='businesssim.products')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('add_employees', models.SmallIntegerField(default=1)),
                ('add_plant_size', models.SmallIntegerField(default=1)),
                ('efficiency_improvement', models.IntegerField(default=10000)),
                ('supplier_relation', models.IntegerField(default=10000)),
                ('raw_material_inventory', models.SmallIntegerField(default=1)),
                ('average_salary', models.IntegerField(default=20000)),
                ('training', models.SmallIntegerField(default=40)),
                ('quality_system', models.IntegerField(default=150000)),
                ('inspection', models.SmallIntegerField(default=15)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_manufacturing', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('State', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('businesssimm_web', models.ManyToManyField(related_name='businesssimm_instructors', to='businesssim.BusinesssimWeb')),
                ('institution', models.ManyToManyField(related_name='institution_instructors', to='businesssim.Institutions')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralLedgers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_general_ledger', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralLedgerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('generalledger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gl_general_ledger_detail', to='businesssim.generalledgers')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('add_equity', models.IntegerField(default=1)),
                ('dividend', models.SmallIntegerField(verbose_name=1)),
                ('add_debt', models.IntegerField(default=1)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_finance', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('type', models.CharField(default='', max_length=25)),
                ('extra_support', models.IntegerField(verbose_name=500000)),
                ('retail_margin', models.SmallIntegerField(verbose_name=35)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_distribution', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_branding', to='businesssim.teams')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
