# Generated by Django 3.1.13 on 2022-09-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0002_auto_20220913_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssimweb',
            old_name='group_name',
            new_name='program_name',
        ),
    ]
