# Generated by Django 3.1.13 on 2022-09-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0003_auto_20220916_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructors',
            old_name='businesssimm_web',
            new_name='businesssim_web',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='businesssimm_web',
            new_name='businesssim_web',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='businesssimm_web',
            new_name='businesssim_web',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='institution',
        ),
        migrations.AddField(
            model_name='instructors',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institution_instructors', to='businesssim.institutions'),
        ),
    ]
