# Generated by Django 3.1.13 on 2022-09-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0004_auto_20220920_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='businesssim_web',
            field=models.ManyToManyField(related_name='businesssim_instructors', to='businesssim.BusinesssimWeb'),
        ),
    ]
