# Generated by Django 3.1.13 on 2022-09-21 01:23

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0005_auto_20220921_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Distributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('type', models.CharField(default='', max_length=25)),
                ('extra_support', models.IntegerField(verbose_name=500000)),
                ('retail_margin', models.SmallIntegerField(verbose_name=35)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('add_equity', models.IntegerField(default=1)),
                ('dividend', models.SmallIntegerField(verbose_name=1)),
                ('add_debt', models.IntegerField(default=1)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralLedgerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Manufacturings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('add_employees', models.SmallIntegerField(default=1)),
                ('add_plant_size', models.SmallIntegerField(default=1)),
                ('efficiency_improvement', models.IntegerField(default=10000)),
                ('supplier_relation', models.IntegerField(default=10000)),
                ('raw_material_inventory', models.SmallIntegerField(default=1)),
                ('average_salary', models.IntegerField(default=20000)),
                ('training', models.SmallIntegerField(default=40)),
                ('quality_system', models.IntegerField(default=150000)),
                ('inspection', models.SmallIntegerField(default=15)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Marketings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('channel', models.CharField(default='', max_length=25)),
                ('amount', models.IntegerField(default=500000)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_marketings', to='businesssim.products')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrialBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=1)),
                ('level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('account', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='team',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='generalledgerdetail',
            name='generalledger',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='team',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='product',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='team',
        ),
        migrations.AlterField(
            model_name='generalledgers',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_generalledgers', to='businesssim.teams'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='businesssim_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesssim_participants', to='businesssim.businesssimweb'),
        ),
        migrations.AlterField(
            model_name='productperiods',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_productperiods', to='businesssim.products'),
        ),
        migrations.AlterField(
            model_name='randdproperties',
            name='randd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='randd_randdproperties', to='businesssim.randds'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='businesssim_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesssim_teams', to='businesssim.businesssimweb'),
        ),
        migrations.DeleteModel(
            name='Branding',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='GeneralLedgerDetail',
        ),
        migrations.DeleteModel(
            name='Manufacturing',
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
        migrations.DeleteModel(
            name='TrialBalance',
        ),
        migrations.AddField(
            model_name='trialbalances',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_trialbalances', to='businesssim.teams'),
        ),
        migrations.AddField(
            model_name='manufacturings',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_manufacturings', to='businesssim.teams'),
        ),
        migrations.AddField(
            model_name='generalledgerdetails',
            name='generalledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generalledger_generalledgerdetails', to='businesssim.generalledgers'),
        ),
        migrations.AddField(
            model_name='finances',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_finances', to='businesssim.teams'),
        ),
        migrations.AddField(
            model_name='distributions',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_distributions', to='businesssim.teams'),
        ),
        migrations.AddField(
            model_name='brandings',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_brandings', to='businesssim.teams'),
        ),
    ]
