# Generated by Django 3.1.13 on 2022-09-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0006_auto_20220921_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructors',
            old_name='State',
            new_name='state',
        ),
    ]
