# Generated by Django 3.1.13 on 2022-09-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0007_auto_20220922_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutions',
            old_name='State',
            new_name='state',
        ),
    ]
