# Generated by Django 3.1.13 on 2022-09-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0008_auto_20220922_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='State',
            new_name='state',
        ),
    ]
