# Generated by Django 3.1.13 on 2022-09-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesssim', '0009_auto_20220922_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssimweb',
            old_name='number_of_participant',
            new_name='number_of_participants',
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='max_participants_in_team',
            field=models.SmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='businesssimweb',
            name='number_of_teams',
            field=models.SmallIntegerField(default=7),
        ),
    ]
