# Generated by Django 3.0.10 on 2021-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0002_auto_20210424_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
