# Generated by Django 3.0.10 on 2021-04-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0004_auto_20210424_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='counter_1_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='counter_2_count',
            field=models.PositiveSmallIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='home',
            name='counter_3_count',
            field=models.PositiveSmallIntegerField(blank=True, default=8),
        ),
        migrations.AlterField(
            model_name='home',
            name='counter_4_count',
            field=models.PositiveSmallIntegerField(blank=True, default=600),
        ),
    ]
