# Generated by Django 3.0.10 on 2021-04-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0005_auto_20210424_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_title_image', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('fab_hose_africa_web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='fabhouseafrica.FabHoseAfricaWeb')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog/section')),
                ('section_title', models.CharField(blank=True, default='', max_length=100)),
                ('section_description', models.CharField(blank=True, default='', max_length=1000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fabhouseafrica.Catalog')),
            ],
            options={
                'verbose_name': 'catalog section',
                'verbose_name_plural': 'catalog sections',
            },
        ),
        migrations.CreateModel(
            name='CatalogSectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(blank=True, default='', max_length=100)),
                ('category_image', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog/section/images')),
                ('category_description', models.CharField(blank=True, default='', max_length=1000)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fabhouseafrica.CatalogSection')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CatalogSectionCategoryStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_title', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_styles', to='fabhouseafrica.CatalogSectionCategory')),
            ],
            options={
                'verbose_name': 'catalog section',
                'verbose_name_plural': 'catalog sections',
            },
        ),
        migrations.CreateModel(
            name='CatalogSectionImageStyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_images', to='fabhouseafrica.CatalogSectionCategoryStyle')),
            ],
            options={
                'verbose_name': 'catalog section image style image',
                'verbose_name_plural': 'catalog section image style images',
            },
        ),
    ]
