# Generated by Django 3.0.10 on 2021-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0007_auto_20210425_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsectionimagestyleimage',
            name='image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog/section/category/style'),
        ),
        migrations.AlterField(
            model_name='catalogsectioncategory',
            name='category_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog/section/category'),
        ),
    ]
