# Generated by Django 3.0.10 on 2021-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0012_auto_20210426_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_us_email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
