# Generated by Django 3.0.10 on 2021-04-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0013_contact_contact_us_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='information',
            new_name='contact',
        ),
    ]
