# Generated by Django 3.0.10 on 2021-04-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0014_auto_20210426_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogsection',
            options={'ordering': ['id'], 'verbose_name': 'catalog section', 'verbose_name_plural': 'catalog sections'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'contact information', 'verbose_name_plural': 'contact information'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='background_title_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='section_background_title_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='section_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/catalog/section/gallery/items')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='fabhouseafrica.Gallery')),
            ],
            options={
                'verbose_name': 'gallery item',
                'verbose_name_plural': 'gallery items',
            },
        ),
    ]
