# Generated by Django 3.0.10 on 2021-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0016_auto_20210427_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitems',
            options={'ordering': ['-image_title'], 'verbose_name': 'gallery item', 'verbose_name_plural': 'gallery items'},
        ),
        migrations.AlterField(
            model_name='galleryitems',
            name='image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/gallery/items'),
        ),
    ]
