# Generated by Django 2.1.10 on 2019-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='sub_transaction',
            field=models.SmallIntegerField(default=1),
        ),
    ]
