# Generated by Django 2.1.10 on 2019-11-02 03:56

import cms.models.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('courses', '0029_auto_20191102_0556'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('globsim', '0002_generalledger_sub_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Please supply the team name.', max_length=50, verbose_name='name')),
                ('slug', models.SlugField(default='', help_text='Please supply the team slug.', max_length=128, verbose_name='slug')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='globsim_team_description', to='cms.Placeholder')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='GSTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', help_text='Please supply the team member slug.', max_length=128, verbose_name='slug')),
                ('course_schedule_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csu_gs_team_members', to='courses.CourseScheduleUser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_team_members', to='globsim.GSTeam')),
            ],
            options={
                'verbose_name': 'team_member',
                'verbose_name_plural': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='GSTeamPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', help_text='Please supply the team member slug.', max_length=128, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'team_period',
                'verbose_name_plural': 'team_periods',
            },
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='bio_short',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='country_city',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='bsinstructor',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bsinstructortranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bsinstructortranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccountstranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chartofaccountstranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='generalledger',
            name='account',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country_city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='description',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='bio_short',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='country_city',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='participanttranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participanttranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rdproject',
            name='period',
        ),
        migrations.RemoveField(
            model_name='rdproject',
            name='team',
        ),
        migrations.RemoveField(
            model_name='rdprojectattributes',
            name='rd_project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teamgrades',
            name='team',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='account',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='assignment_method',
            field=models.IntegerField(choices=[(0, 'Other'), (5, 'Random'), (10, 'Individual')], default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='course_schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSchedule'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_students_per_team',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='period',
            name='slug',
            field=models.SlugField(default='', help_text='Please supply the period slug.', max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='period',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_periods', to='globsim.Game'),
        ),
        migrations.DeleteModel(
            name='BSInstructor',
        ),
        migrations.DeleteModel(
            name='BSInstructorTranslation',
        ),
        migrations.DeleteModel(
            name='ChartOfAccounts',
        ),
        migrations.DeleteModel(
            name='ChartOfAccountsTranslation',
        ),
        migrations.DeleteModel(
            name='CountryCity',
        ),
        migrations.DeleteModel(
            name='GeneralLedger',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='ParticipantTranslation',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RDProject',
        ),
        migrations.DeleteModel(
            name='RDProjectAttributes',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamGrades',
        ),
        migrations.DeleteModel(
            name='TrialBalance',
        ),
        migrations.AddField(
            model_name='gsteamperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_team_periods', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='gsteamperiod',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_team_periods', to='globsim.GSTeam'),
        ),
        migrations.AddField(
            model_name='gsteam',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='globsim.Game'),
        ),
        migrations.AddField(
            model_name='gsteam',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
