# Generated by Django 2.1.10 on 2019-11-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0003_auto_20191102_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsteammember',
            name='slug',
        ),
    ]
