# Generated by Django 2.1.10 on 2020-04-09 18:39

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('globsim', '0004_remove_gsteammember_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='attribute_description', to='cms.Placeholder')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the section name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the section slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Attribute')),
            ],
            options={
                'verbose_name': 'attribute Translation',
                'db_table': 'globsim_attribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GameTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the game name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the game slug.', max_length=128, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'game Translation',
                'db_table': 'globsim_game_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='game_type_description', to='cms.Placeholder')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'game type',
                'verbose_name_plural': 'game types',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GameTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the game type.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the game type slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.GameType')),
            ],
            options={
                'verbose_name': 'game type Translation',
                'db_table': 'globsim_gametype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PeriodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the section name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the section slug.', max_length=128, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'period Translation',
                'db_table': 'globsim_period_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the product name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the product slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'globsim_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RandD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RandDTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the R and D name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the R and D slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.RandD')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'globsim_randd_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='segment_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SegmentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the segment name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the segment slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Segment')),
            ],
            options={
                'verbose_name': 'segment Translation',
                'db_table': 'globsim_segment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='gsteam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gsteam',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gsteam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gsteammember',
            name='course_schedule_user',
        ),
        migrations.RemoveField(
            model_name='gsteammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='gsteamperiod',
            name='period',
        ),
        migrations.RemoveField(
            model_name='gsteamperiod',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id'], 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='assignment_method',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_students_per_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_students',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_teams',
        ),
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.RemoveField(
            model_name='period',
            name='slug',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='game_description', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_periods',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='period',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='globsim.Game'),
        ),
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='GSTeam',
        ),
        migrations.DeleteModel(
            name='GSTeamMember',
        ),
        migrations.DeleteModel(
            name='GSTeamPeriod',
        ),
        migrations.AddField(
            model_name='randd',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds', to='globsim.Game'),
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='globsim.Game'),
        ),
        migrations.AddField(
            model_name='periodtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='gametranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Game'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='globsim.Segment'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='globsim.GameType'),
        ),
        migrations.AlterUniqueTogether(
            name='segmenttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='randdtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='periodtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='gametypetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='gametranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
