# Generated by Django 2.1.10 on 2020-04-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0005_auto_20200409_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='is_current',
        ),
        migrations.AddField(
            model_name='game',
            name='current_period',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='period_type',
            field=models.IntegerField(choices=[(0, 'Year'), (5, 'Period')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='course_schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='courses.CourseSchedule'),
        ),
    ]
