# Generated by Django 2.1.10 on 2020-04-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0006_auto_20200418_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_period',
            new_name='current_period_number',
        ),
    ]
