# Generated by Django 2.1.10 on 2020-04-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0007_auto_20200418_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='course_schedule',
        ),
    ]
