# Generated by Django 2.1.10 on 2020-04-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20200418_0804'),
        ('globsim', '0009_game_course_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandD_Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='periodtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='randdtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='randdtranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='randd',
            options={'verbose_name': 'R and D Project', 'verbose_name_plural': 'R and D Projects'},
        ),
        migrations.RemoveField(
            model_name='randd',
            name='product',
        ),
        migrations.AddField(
            model_name='attribute',
            name='start_optimal_value',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attribute',
            name='tau_improvments',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='attribute',
            name='tau_miss_match',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_products', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='product',
            name='randd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randd_products', to='globsim.RandD'),
        ),
        migrations.AddField(
            model_name='randd',
            name='name',
            field=models.CharField(default='', help_text='Please supply the R and D name.', max_length=128, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='randd',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_rds', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='randd',
            name='prime_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='randd',
            name='project_expenditure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='randd',
            name='scu_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='randd',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_rds', to='globsim.Segment'),
        ),
        migrations.AddField(
            model_name='randd',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_rds', to='courses.Team'),
        ),
        migrations.AlterField(
            model_name='period',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_periods', to='globsim.Game'),
        ),
        migrations.AlterField(
            model_name='product',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_products', to='globsim.Game'),
        ),
        migrations.DeleteModel(
            name='PeriodTranslation',
        ),
        migrations.DeleteModel(
            name='RandDTranslation',
        ),
        migrations.AddField(
            model_name='randd_attribute',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_randds', to='globsim.Attribute'),
        ),
        migrations.AddField(
            model_name='randd_attribute',
            name='randd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randd_attributes', to='globsim.RandD'),
        ),
    ]
