# Generated by Django 2.1.10 on 2020-04-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0010_auto_20200426_2009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='ProductTranslation',
        ),
    ]
