# Generated by Django 2.1.10 on 2020-04-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0011_auto_20200426_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randd_attribute',
            options={'verbose_name': 'randd_attribute', 'verbose_name_plural': 'randd_attributes'},
        ),
    ]
