# Generated by Django 2.1.10 on 2020-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0012_auto_20200426_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randd',
            name='prime_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
