# Generated by Django 2.1.10 on 2020-04-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globsim', '0013_auto_20200426_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randd',
            options={'ordering': ['period'], 'verbose_name': 'R and D Project', 'verbose_name_plural': 'R and D Projects'},
        ),
        migrations.AddField(
            model_name='randd',
            name='last_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_randds', to=settings.AUTH_USER_MODEL),
        ),
    ]
