# Generated by Django 2.1.10 on 2020-05-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0014_auto_20200427_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randd',
            options={'ordering': ['-period'], 'verbose_name': 'R and D Project', 'verbose_name_plural': 'R and D Projects'},
        ),
    ]
