# Generated by Django 2.1.10 on 2020-05-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0015_auto_20200510_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPeriodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('planned_production', models.IntegerField(default=0)),
                ('planned_safely_stock', models.IntegerField(default=0)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_products_data', to='globsim.Period')),
            ],
            options={
                'verbose_name': 'product data',
                'verbose_name_plural': 'products data',
            },
        ),
        migrations.CreateModel(
            name='ProductPeriodDataDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('type', models.IntegerField(choices=[(0, 'Advertising_TV'), (5, 'Advertising_internet'), (10, 'Advertising_magazine'), (100, 'PublicRelation_TV'), (105, 'PublicRelation_internet'), (110, 'PublicRelation_magazine')], default=0)),
                ('product_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_period_data_details', to='globsim.ProductPeriodData')),
            ],
            options={
                'verbose_name': 'product data detail',
                'verbose_name_plural': 'products data detail',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='period',
        ),
        migrations.AddField(
            model_name='product',
            name='abundant_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abundant_period_products', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_period_products', to='globsim.Period'),
        ),
        migrations.AddField(
            model_name='productperioddata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_periods_data', to='globsim.Product'),
        ),
    ]
