# Generated by Django 2.1.10 on 2020-05-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0016_auto_20200524_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='productperioddata',
            name='randd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randd_products_period', to='globsim.RandD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_products', to='courses.Team'),
        ),
    ]
