# Generated by Django 2.1.10 on 2020-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0017_auto_20200524_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='Please supply the Product name.', max_length=128, null=True, verbose_name='name'),
        ),
    ]
