# Generated by Django 2.1.10 on 2020-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0018_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='productperioddata',
            name='planned_production',
        ),
        migrations.RemoveField(
            model_name='productperioddata',
            name='planned_safely_stock',
        ),
        migrations.RemoveField(
            model_name='productperioddata',
            name='randd',
        ),
        migrations.RemoveField(
            model_name='productperioddata',
            name='retail_price',
        ),
        migrations.AlterField(
            model_name='productperioddata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productperioddatadetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productperioddatadetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productperioddatadetail',
            name='type',
            field=models.IntegerField(choices=[(0, 'Advertising_TV'), (5, 'Advertising_internet'), (10, 'Advertising_magazine'), (100, 'PublicRelation_TV'), (105, 'PublicRelation_internet'), (110, 'PublicRelation_magazine'), (200, 'Product_retail_price'), (210, 'Product_planned_production'), (220, 'Product_planned_safely_stock'), (220, 'Product_randd')], default=0),
        ),
    ]
