# Generated by Django 2.1.10 on 2020-06-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20200510_0420'),
        ('globsim', '0019_auto_20200530_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Please supply the HR name.', max_length=128, null=True, verbose_name='name')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_human_resources', to='courses.Team')),
            ],
            options={
                'verbose_name': 'manufacturing',
                'verbose_name_plural': 'manufacturing',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HumanResourcesPeriodData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_periods_data', to='globsim.HumanResources')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_human_resources_data', to='globsim.Period')),
            ],
            options={
                'verbose_name': 'hr data',
                'verbose_name_plural': 'hr data',
            },
        ),
        migrations.CreateModel(
            name='HumanResourcesPeriodDataDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('type', models.IntegerField(choices=[(10, 'Quality_average_salary'), (20, 'Quality_training'), (30, 'Quality_benefits'), (110, 'Quality_number_of_managers'), (110, 'Quality_number_of_employees')], default=0)),
                ('human_resources_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_period_data_details', to='globsim.HumanResourcesPeriodData')),
            ],
            options={
                'verbose_name': 'hr data detail',
                'verbose_name_plural': 'hr data detail',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Please supply the Manufacturing name.', max_length=128, null=True, verbose_name='name')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_manufacturing', to='courses.Team')),
            ],
            options={
                'verbose_name': 'manufacturing',
                'verbose_name_plural': 'manufacturings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingPeriodData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_periods_data', to='globsim.Manufacturing')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_manufacturing_data', to='globsim.Period')),
            ],
            options={
                'verbose_name': 'manufacturing data',
                'verbose_name_plural': 'manufacturing data',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingPeriodDataDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('type', models.IntegerField(choices=[(10, 'Process_technology_improvement'), (20, 'Process_supply_chain_management_system'), (30, 'Process_warehousing'), (110, 'Plant_size'), (210, 'Quality_internal_control')], default=0)),
                ('manufacturing_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_period_data_details', to='globsim.ManufacturingPeriodData')),
            ],
            options={
                'verbose_name': 'product data detail',
                'verbose_name_plural': 'products data detail',
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='productperioddatadetail',
            options={'ordering': ['type'], 'verbose_name': 'product data detail', 'verbose_name_plural': 'products data detail'},
        ),
        migrations.AlterField(
            model_name='productperioddatadetail',
            name='type',
            field=models.IntegerField(choices=[(10, 'Advertising_TV'), (20, 'Advertising_internet'), (30, 'Advertising_magazine'), (110, 'PublicRelation_TV'), (120, 'PublicRelation_internet'), (130, 'PublicRelation_magazine'), (204, 'Product_retail_price'), (208, 'Product_planned_production'), (212, 'Product_inventory_finished_goods'), (216, 'Product_inventory_raw_material'), (220, 'Product_quality_system'), (224, 'Product_quality_inspection'), (230, 'Product_randd')], default=0),
        ),
    ]
