# Generated by Django 2.1.10 on 2020-06-06 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20200510_0420'),
        ('globsim', '0020_auto_20200604_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresources',
            name='team',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='team',
        ),
        migrations.RemoveField(
            model_name='humanresourcesperioddata',
            name='human_resources',
        ),
        migrations.RemoveField(
            model_name='manufacturingperioddata',
            name='manufacturing',
        ),
        migrations.AddField(
            model_name='humanresourcesperioddata',
            name='team',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_human_resources', to='courses.Team'),
        ),
        migrations.AddField(
            model_name='manufacturingperioddata',
            name='team',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_manufacturing', to='courses.Team'),
        ),
        migrations.DeleteModel(
            name='HumanResources',
        ),
        migrations.DeleteModel(
            name='Manufacturing',
        ),
    ]
