# Generated by Django 2.1.10 on 2020-06-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0021_auto_20200606_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingperioddatadetail',
            options={'ordering': ['type'], 'verbose_name': 'manufacturing data detail', 'verbose_name_plural': 'manufacturing data details'},
        ),
        migrations.AlterField(
            model_name='humanresourcesperioddata',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_human_resources', to='courses.Team'),
        ),
        migrations.AlterField(
            model_name='manufacturingperioddata',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_manufacturing', to='courses.Team'),
        ),
    ]
