# Generated by Django 2.1.10 on 2020-06-07 15:38

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('globsim', '0022_auto_20200606_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='distributor_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'distributor',
                'verbose_name_plural': 'distributors',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DistributorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the distributor name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the distributor slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Distributor')),
            ],
            options={
                'verbose_name': 'distributor Translation',
                'db_table': 'globsim_distributor_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='humanresourcesperioddatadetail',
            name='type',
            field=models.IntegerField(choices=[(10, 'Quality_average_salary'), (20, 'Quality_training'), (30, 'Quality_benefits'), (110, 'Quality_number_of_managers'), (120, 'Quality_number_of_employees')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='distributortranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
