# Generated by Django 2.1.10 on 2020-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0024_auto_20200608_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributorsegment',
            options={'verbose_name': 'distributor_segment', 'verbose_name_plural': 'distributor_segments'},
        ),
        migrations.AddField(
            model_name='distributorattribute',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
