# Generated by Django 2.1.10 on 2020-06-09 04:21

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0025_auto_20200608_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePeriodDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_number', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_schedule_period_dates', to='globsim.Game')),
            ],
            options={
                'verbose_name': 'period_date',
                'verbose_name_plural': 'periods_date',
                'ordering': ['-id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='period',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='period',
            name='period_start',
        ),
    ]
