# Generated by Django 2.1.10 on 2020-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0026_auto_20200609_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleperioddate',
            options={'ordering': ['id'], 'verbose_name': 'schedule_period_date', 'verbose_name_plural': 'schedule_period_date'},
        ),
        migrations.RemoveField(
            model_name='gdistributor',
            name='created_period',
        ),
        migrations.AddField(
            model_name='gdistributor',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='humanresourcesperioddatadetail',
            name='type',
            field=models.IntegerField(choices=[(10, 'Salary_employee_salary'), (20, 'Salary_manager_salary'), (30, 'Salary_number_of_managers'), (40, 'Salary_number_of_employees'), (50, 'Salary_benefits'), (110, 'Quality_employee_training'), (120, 'Quality_manager_training')], default=0),
        ),
        migrations.AlterField(
            model_name='scheduleperioddate',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
