# Generated by Django 2.1.10 on 2020-06-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0027_auto_20200611_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdistributorperioddatadetail',
            options={'ordering': ['distributor_attribute'], 'verbose_name': 'g_distributor_data_detail', 'verbose_name_plural': 'g_distributor_data_details'},
        ),
        migrations.RenameField(
            model_name='distributorattribute',
            old_name='amount',
            new_name='min',
        ),
        migrations.RemoveField(
            model_name='gdistributorperioddatadetail',
            name='type',
        ),
        migrations.AddField(
            model_name='distributor',
            name='logistic_support',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='distributor',
            name='number_of_location',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='distributorattribute',
            name='max',
            field=models.SmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='gdistributorperioddatadetail',
            name='distributor_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_distributor_attribute_period_data_details', to='globsim.DistributorAttribute'),
        ),
    ]
