# Generated by Django 2.1.10 on 2020-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0028_auto_20200612_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorattribute',
            name='max',
            field=models.IntegerField(default=200),
        ),
    ]
