# Generated by Django 2.1.10 on 2020-06-13 00:09

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('courses', '0053_auto_20200510_0420'),
        ('globsim', '0029_auto_20200612_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'finance',
                'verbose_name_plural': 'finances',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinancePeriodData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_periods_data', to='globsim.Finance')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_finances_data', to='globsim.Period')),
            ],
            options={
                'verbose_name': 'finance_data',
                'verbose_name_plural': 'finances_data',
            },
        ),
        migrations.CreateModel(
            name='FinancePeriodDataDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'finance_data_detail',
                'verbose_name_plural': 'finance_data_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='finance_type_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_types', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'finance_type',
                'verbose_name_plural': 'finance_types',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinanceTypeAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='attribute_description', to='cms.Placeholder')),
                ('finance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_attributes', to='globsim.FinanceType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'finance_type_attribute',
                'verbose_name_plural': 'finance_type_attributes',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinanceTypeAttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the section name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the section slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.FinanceTypeAttribute')),
            ],
            options={
                'verbose_name': 'finance_type_attribute Translation',
                'db_table': 'globsim_financetypeattribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FinanceTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the finance type name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the finance type slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.FinanceType')),
            ],
            options={
                'verbose_name': 'finance_type Translation',
                'db_table': 'globsim_financetype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='gdistributorperioddata',
            options={'verbose_name': 'g_distributor_data', 'verbose_name_plural': 'g_distributors_data'},
        ),
        migrations.AddField(
            model_name='financeperioddatadetail',
            name='finance_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_type_periods_detail', to='globsim.FinanceTypeAttribute'),
        ),
        migrations.AddField(
            model_name='financeperioddatadetail',
            name='finance_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_period_data_details', to='globsim.FinancePeriodData'),
        ),
        migrations.AddField(
            model_name='finance',
            name='finance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='globsim.FinanceType'),
        ),
        migrations.AddField(
            model_name='finance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_finances', to='courses.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='financetypetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='financetypeattributetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
