# Generated by Django 2.1.10 on 2020-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0030_auto_20200613_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetypeattribute',
            name='max',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='financetypeattribute',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
