# Generated by Django 2.1.10 on 2020-06-13 23:09

import academycity.apps.core.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('globsim', '0031_auto_20200613_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='product_type_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'product_type',
                'verbose_name_plural': 'product_types',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTypeAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', academycity.apps.core.fields.OrderField(blank=True, default=1)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=200)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='attribute_description', to='cms.Placeholder')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='globsim.ProductType')),
            ],
            options={
                'verbose_name': 'product_type_attribute',
                'verbose_name_plural': 'product_type_attributes',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTypeAttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply product attribute type.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply product attribute slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.ProductTypeAttribute')),
            ],
            options={
                'verbose_name': 'product_type_attribute Translation',
                'db_table': 'globsim_producttypeattribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply the product type name.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply the product type slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.ProductType')),
            ],
            options={
                'verbose_name': 'product_type Translation',
                'db_table': 'globsim_producttype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttypetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='producttypeattributetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
