# Generated by Django 2.1.10 on 2020-06-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0032_auto_20200614_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='image',
        ),
        migrations.AlterUniqueTogether(
            name='producttypetranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producttypetranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='producttypeattribute',
            options={'ordering': ['id'], 'verbose_name': 'product_type_attribute', 'verbose_name_plural': 'product_type_attributes'},
        ),
        migrations.RemoveField(
            model_name='producttypeattribute',
            name='order',
        ),
        migrations.RemoveField(
            model_name='producttypeattribute',
            name='product_type',
        ),
        migrations.AddField(
            model_name='producttypeattribute',
            name='account',
            field=models.CharField(default='', help_text='Please supply account.', max_length=128, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='producttypeattribute',
            name='category',
            field=models.CharField(default='', help_text='Please supply category.', max_length=128, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='producttypeattribute',
            name='segment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='globsim.Segment'),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='ProductTypeTranslation',
        ),
    ]
