# Generated by Django 2.1.10 on 2020-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0033_auto_20200614_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeattribute',
            name='account_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
