# Generated by Django 2.1.10 on 2020-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0034_auto_20200614_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeattribute',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
