# Generated by Django 2.1.10 on 2020-06-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0035_producttypeattribute_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productperioddatadetail',
            options={'ordering': ['id'], 'verbose_name': 'product data detail', 'verbose_name_plural': 'products data detail'},
        ),
        migrations.RemoveField(
            model_name='productperioddatadetail',
            name='type',
        ),
        migrations.AddField(
            model_name='productperioddatadetail',
            name='product_type_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_ppdds', to='globsim.ProductTypeAttribute'),
        ),
    ]
