# Generated by Django 2.1.10 on 2020-06-15 15:41

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('globsim', '0036_auto_20200615_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResourcesTypeAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='', help_text='Please supply category.', max_length=128, verbose_name='category')),
                ('account', models.CharField(default='', help_text='Please supply account.', max_length=128, verbose_name='account')),
                ('account_number', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=200)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='attribute_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_attributes', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'human_resources_type_attribute',
                'verbose_name_plural': 'human_resources_type_attributes',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HumanResourcesTypeAttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply product attribute type.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply product attribute slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.HumanResourcesTypeAttribute')),
            ],
            options={
                'verbose_name': 'human_resources_type_attribute Translation',
                'db_table': 'globsim_humanresourcestypeattribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ManufacturingTypeAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='', help_text='Please supply category.', max_length=128, verbose_name='category')),
                ('account', models.CharField(default='', help_text='Please supply account.', max_length=128, verbose_name='account')),
                ('account_number', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=200)),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='attribute_description', to='cms.Placeholder')),
                ('game_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_attributes', to='globsim.GameType')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'manufacturing_type_attribute',
                'verbose_name_plural': 'manufacturing_type_attributes',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManufacturingTypeAttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', help_text='Please supply manuf. attribute type.', max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Please supply manuf. attribute slug.', max_length=128, verbose_name='slug')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.ManufacturingTypeAttribute')),
            ],
            options={
                'verbose_name': 'manufacturing_type_attribute Translation',
                'db_table': 'globsim_manufacturingtypeattribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='humanresourcesperioddatadetail',
            options={'ordering': ['id'], 'verbose_name': 'human resource data detail', 'verbose_name_plural': 'human resources data detail'},
        ),
        migrations.AlterModelOptions(
            name='manufacturingperioddatadetail',
            options={'ordering': ['id'], 'verbose_name': 'manufacturing data detail', 'verbose_name_plural': 'manufacturing data details'},
        ),
        migrations.RemoveField(
            model_name='humanresourcesperioddatadetail',
            name='type',
        ),
        migrations.RemoveField(
            model_name='manufacturingperioddatadetail',
            name='type',
        ),
        migrations.AddField(
            model_name='humanresourcesperioddatadetail',
            name='human_resource_type_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_hpdds', to='globsim.HumanResourcesTypeAttribute'),
        ),
        migrations.AddField(
            model_name='manufacturingperioddatadetail',
            name='manufacturing_type_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mpdds', to='globsim.ManufacturingTypeAttribute'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturingtypeattributetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='humanresourcestypeattributetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
