# Generated by Django 2.1.10 on 2020-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0037_auto_20200615_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanresourcesperioddata',
            options={'verbose_name': 'human resources data', 'verbose_name_plural': 'human resources data'},
        ),
        migrations.AddField(
            model_name='distributorattribute',
            name='account',
            field=models.CharField(default='', help_text='Please supply account.', max_length=128, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='distributorattribute',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
