# Generated by Django 2.1.10 on 2020-06-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0038_auto_20200617_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorattribute',
            name='account',
        ),
    ]
