# Generated by Django 2.1.10 on 2020-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0039_remove_distributorattribute_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetypeattribute',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
