# Generated by Django 3.0.10 on 2020-11-07 22:27

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('globsim', '0040_financetypeattribute_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Attribute'),
        ),
        migrations.AlterField(
            model_name='distributorattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.DistributorAttribute'),
        ),
        migrations.AlterField(
            model_name='distributortranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Distributor'),
        ),
        migrations.AlterField(
            model_name='financetypeattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.FinanceTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='financetypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.FinanceType'),
        ),
        migrations.AlterField(
            model_name='gametranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Game'),
        ),
        migrations.AlterField(
            model_name='gametypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.GameType'),
        ),
        migrations.AlterField(
            model_name='humanresourcestypeattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.HumanResourcesTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='manufacturingtypeattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.ManufacturingTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='producttypeattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.ProductTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='segmenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='globsim.Segment'),
        ),
    ]
