# Generated by Django 3.1.13 on 2025-06-11 09:55

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country_cc', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('measure_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MeasureGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RangeDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimeDim',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelImpFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_relimp_fact', to='el.measuredim')),
                ('measure_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_group_dim_relimp_fact', to='el.measuregroupdim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_relimp_fact', to='el.rangedim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_relimp_fact', to='el.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OutputFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(blank=True, default='min', max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_output_fact', to='el.countrydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_output_fact', to='el.measuredim')),
                ('range_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='range_dim_output_fact', to='el.rangedim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_output_fact', to='el.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MinMaxCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=24, null=True)),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_min_max_cut', to='el.measuredim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_min_max_cut', to='el.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='measuredim',
            name='measure_group_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_world_Bank_fact', to='el.measuregroupdim'),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('country_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_world_Bank_fact', to='el.countrydim')),
                ('measure_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_dim_world_Bank_fact', to='el.measuredim')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_world_Bank_fact', to='el.timedim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='countrydim',
            name='country_group_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_dim_group_dim', to='el.countrygroupdim'),
        ),
    ]
