# Generated by Django 3.1.11 on 2021-07-05 11:58

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('education', '0024_morenewsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.placeholder'),
        ),
    ]
