# Generated by Django 3.0.10 on 2021-02-22 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='swot', max_length=100)),
                ('swot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_swot_clocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SWOTClockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(blank=True, default='', max_length=50)),
                ('field_value', models.CharField(blank=True, default='', max_length=50)),
                ('swot_clock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot_clock_data', to='swotclock.SWOTClock')),
            ],
        ),
    ]
