# Generated by Django 3.0.10 on 2021-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swotclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotclockdata',
            name='field_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
