# Generated by Django 3.1.13 on 2022-02-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javascripttutorial', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTabs',
        ),
    ]
