# Generated by Django 3.0.10 on 2021-04-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabHoseAfricaWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_logo', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web')),
            ],
            options={
                'verbose_name': 'fab_hose_africa_web',
                'verbose_name_plural': 'fab_hose_africa_webs',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_map', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hHose_africa_web/home')),
                ('image_moving', models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/home')),
                ('fab_hose_africa_web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='fabhouseafrica.FabHoseAfricaWeb')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
    ]
