# Generated by Django 3.0.10 on 2021-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0003_fabhoseafricaweb_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_our_products',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='background_1',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/home'),
        ),
        migrations.AddField(
            model_name='home',
            name='background_2',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/home'),
        ),
        migrations.AddField(
            model_name='home',
            name='call_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='call_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_1_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_1_title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_2_count',
            field=models.PositiveSmallIntegerField(blank=True, default=2, max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_2_title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_3_count',
            field=models.PositiveSmallIntegerField(blank=True, default=8, max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_3_title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_4_count',
            field=models.PositiveSmallIntegerField(blank=True, default=600, max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='counter_4_title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='email_inquire_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='email_inquire_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='email_sale_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='email_sale_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='left_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/home'),
        ),
        migrations.AddField(
            model_name='home',
            name='little_about_us',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='office_address_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='office_address_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='opening_hours_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='opening_hours_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='right_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/home'),
        ),
    ]
