# Generated by Django 3.0.10 on 2021-04-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0006_catalog_catalogsection_catalogsectioncategory_catalogsectioncategorystyle_catalogsectionimagestyleim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogsectioncategorystyle',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
        migrations.AlterModelOptions(
            name='catalogsectionimagestyleimage',
            options={'verbose_name': 'style_image', 'verbose_name_plural': 'style_images'},
        ),
        migrations.RenameField(
            model_name='catalogsectionimagestyleimage',
            old_name='image',
            new_name='style',
        ),
    ]
