# Generated by Django 3.0.10 on 2021-04-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0009_auto_20210425_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsectioncategory',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='fabhouseafrica.CatalogSection'),
        ),
    ]
