# Generated by Django 3.0.10 on 2021-04-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0010_auto_20210425_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='call_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='call_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='email_inquire_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='email_inquire_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='email_sale_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='email_sale_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='office_address_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='office_address_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='opening_hours_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='opening_hours_2',
        ),
        migrations.AddField(
            model_name='catalogsectioncategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='call_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='call_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='email_inquire_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='email_inquire_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='email_sale_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='email_sale_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='office_address_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='office_address_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='opening_hours_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fabhoseafricaweb',
            name='opening_hours_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_hose_africa_web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='fabhouseafrica.FabHoseAfricaWeb')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_hose_africa_web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='fabhouseafrica.FabHoseAfricaWeb')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_hose_africa_web', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='fabhouseafrica.FabHoseAfricaWeb')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
    ]
