# Generated by Django 3.0.10 on 2021-04-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0011_auto_20210426_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='background_1',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='background_title_image',
            field=models.ImageField(default='fab_hose_africa_web/no_image.png', upload_to='fab_hose_africa_web/contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='information_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_message_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ReceivedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='fabhouseafrica.Contact')),
            ],
            options={
                'verbose_name': 'received_message',
                'verbose_name_plural': 'received_messages',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='fabhouseafrica.Contact')),
            ],
            options={
                'verbose_name': 'information',
                'verbose_name_plural': 'information',
            },
        ),
    ]
