# Generated by Django 3.0.10 on 2021-04-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabhouseafrica', '0015_auto_20210427_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitems',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='fabhouseafrica.Gallery'),
        ),
    ]
