# Generated by Django 2.1.10 on 2019-11-02 04:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('courses', '0029_auto_20191102_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('period_start', models.DateTimeField(auto_now=True)),
                ('period_end', models.DateTimeField(auto_now=True)),
                ('assignment_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', help_text='Please supply the assignment slug.', max_length=128, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='CVTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Please supply the team name.', max_length=50, verbose_name='name')),
                ('slug', models.SlugField(default='', help_text='Please supply the team slug.', max_length=128, verbose_name='slug')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='CVTeamAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', help_text='Please supply the team member slug.', max_length=128, verbose_name='slug')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_team_assignments', to='corporatevaluation.Assignment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_team_assignments', to='corporatevaluation.CVTeam')),
            ],
            options={
                'verbose_name': 'team_assignment',
                'verbose_name_plural': 'team_assignments',
            },
        ),
        migrations.CreateModel(
            name='CVTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csu_cv_team_members', to='courses.CourseScheduleUser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_team_members', to='corporatevaluation.CVTeam')),
            ],
            options={
                'verbose_name': 'team_member',
                'verbose_name_plural': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('number_of_teams', models.IntegerField(default=10)),
                ('number_of_students', models.IntegerField(default=50)),
                ('number_of_students_per_team', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (5, 'Approved'), (10, 'Student Registration'), (20, 'End Registration'), (30, 'Running'), (100, 'Finished')], default=0)),
                ('assignment_method', models.IntegerField(choices=[(0, 'Other'), (5, 'Random'), (10, 'Individual')], default=10)),
                ('course_schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSchedule')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.AddField(
            model_name='cvteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='corporatevaluation.Project'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='corporatevaluation.Project'),
        ),
    ]
