# Generated by Django 2.1.10 on 2019-12-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20191118_0116'),
        ('corporatevaluation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ticker', models.CharField(max_length=10)),
                ('current_year', models.SmallIntegerField()),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('number_of_shares', models.IntegerField()),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('excess_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('preferred_stock', models.DecimalField(decimal_places=2, max_digits=18)),
                ('market_value_equity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('equity_attributable_to_oncontrolling_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDataTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_data_time_series', to='courses.Team')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adj_default_spread', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('country_risk_premium', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('total_risk_premium', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('region', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_rating', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('default_spread', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalIndustryAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('number_of_firms', models.PositiveIntegerField(default=1)),
                ('unlevered_beta_corrected_for_cash', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('market_d_over_e_ratio', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('market_debt_to_capital', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('effective_tax_rate', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('dividend_payout', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('net_margin', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('pre_tax_operating_margin', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('roe', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('roic', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('SalesOverCapital', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('ev_over_sales', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('revenue_growth_rateLast_5_years', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
                ('expected_earnings_growth_next_5_years', models.DecimalField(decimal_places=4, default=1, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RBOIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ic', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('to_ic', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('rating', models.CharField(default='', max_length=100)),
                ('spread', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cvteam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cvteam',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cvteamassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='cvteamassignment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='cvteammember',
            name='course_schedule_user',
        ),
        migrations.RemoveField(
            model_name='cvteammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assignment_method',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number_of_students',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number_of_students_per_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number_of_teams',
        ),
        migrations.AddField(
            model_name='project',
            name='mature_marker_risk_premium',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=8),
        ),
        migrations.AddField(
            model_name='project',
            name='rf',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=8),
        ),
        migrations.AddField(
            model_name='project',
            name='volatility_ratio',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (5, 'Approved'), (30, 'Running'), (100, 'Finished')], default=0),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='CVTeam',
        ),
        migrations.DeleteModel(
            name='CVTeamAssignment',
        ),
        migrations.DeleteModel(
            name='CVTeamMember',
        ),
        migrations.AddField(
            model_name='country',
            name='long_term_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporatevaluation.CountryRating'),
        ),
        migrations.AddField(
            model_name='companydatatimeseries',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.CompanyDataType'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.Country'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.GlobalIndustryAverages'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='courses.Team'),
        ),
    ]
