# Generated by Django 2.1.10 on 2019-12-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0002_auto_20191227_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRigion',
            fields=[
                ('pkey_rigion', models.AutoField(primary_key=True, serialize=False)),
                ('rigion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='adj_default_spread',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_risk_premium',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='total_risk_premium',
        ),
        migrations.RemoveField(
            model_name='countryrating',
            name='id',
        ),
        migrations.AddField(
            model_name='countryrating',
            name='pkey_country_rating',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='long_term_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_countries', to='corporatevaluation.CountryRating'),
        ),
        migrations.AlterField(
            model_name='rboic',
            name='from_ic',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rboic',
            name='spread',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rboic',
            name='to_ic',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='country',
            name='rigion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='region_countries', to='corporatevaluation.CountryRigion'),
        ),
    ]
