# Generated by Django 2.1.10 on 2019-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0003_auto_20191229_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='marginal_tax_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='countryrating',
            name='default_spread',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
    ]
