# Generated by Django 2.1.10 on 2019-12-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0004_auto_20191229_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryRigion',
            new_name='CountryRegion',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='rigion',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='countryregion',
            old_name='pkey_rigion',
            new_name='pkey_region',
        ),
        migrations.RenameField(
            model_name='countryregion',
            old_name='rigion',
            new_name='region',
        ),
    ]
