# Generated by Django 2.1.10 on 2019-12-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0005_auto_20191230_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mature_marker_risk_premium',
            field=models.DecimalField(decimal_places=4, default=0.0525, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='rf',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='volatility_ratio',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=8),
        ),
    ]
