# Generated by Django 2.1.10 on 2019-12-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20191118_0116'),
        ('corporatevaluation', '0006_auto_20191230_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10, null=True)),
                ('sic_code', models.SmallIntegerField(default=0)),
                ('sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.SmallIntegerField()),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('number_of_shares', models.IntegerField()),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('excess_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('preferred_stock', models.DecimalField(decimal_places=2, max_digits=18)),
                ('market_value_equity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('equity_attributable_to_oncontrolling_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='courses.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='company_ticker',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='excess_cash',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='team',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='total_debt',
        ),
        migrations.AddField(
            model_name='companydata',
            name='cash_cash_equivalents',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='companydata',
            name='long_term_debt_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='companydata',
            name='noncurrent_liabilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='companydata',
            name='year',
            field=models.SmallIntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='ebit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='equity_attributable_to_oncontrolling_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='interest_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='market_value_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='number_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='preferred_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='companydata',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.CompanyInfo'),
        ),
    ]
