# Generated by Django 2.1.10 on 2020-01-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0008_auto_20200101_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcompany',
            name='company_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.CompanyInfo'),
        ),
        migrations.AddField(
            model_name='teamcompany',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.GlobalIndustryAverages'),
        ),
    ]
