# Generated by Django 2.1.10 on 2020-01-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0009_auto_20200101_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='intangible_assets_net_iad',
            new_name='intangible_assets_net',
        ),
    ]
