# Generated by Django 2.1.10 on 2020-01-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0010_auto_20200101_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('sic_code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='sic_code',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='sic_description',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.Industry'),
        ),
    ]
