# Generated by Django 2.1.10 on 2020-01-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0011_auto_20200104_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='number_of_shares',
            field=models.BigIntegerField(default=0),
        ),
    ]
