# Generated by Django 2.1.10 on 2020-01-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0013_auto_20200109_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='stockholders_quity',
            new_name='stockholders_equity',
        ),
    ]
