# Generated by Django 2.1.10 on 2020-04-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0016_auto_20200409_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course_schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='courses.CourseSchedule'),
        ),
    ]
