# Generated by Django 2.1.10 on 2020-04-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0017_auto_20200418_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course_schedule',
        ),
    ]
