# Generated by Django 2.1.10 on 2020-04-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0020_auto_20200418_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='cash_cash_equivalents',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='ebitda',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='enterprise_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='equity_attributable_to_oncontrolling_interest',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='goodwill',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='income_taxes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='intangible_assets_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='interest_expense',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='long_term_debt_noncurrent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='market_value_equity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='noncurrent_liabilities',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='preferred_stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='stockholders_equity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_long_term_debt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
