# Generated by Django 2.1.10 on 2020-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0022_auto_20200419_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='interest_coverage_ratio',
        ),
        migrations.AddField(
            model_name='companydata',
            name='nofy_for_roic_et',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companydata',
            name='snofy',
            field=models.SmallIntegerField(default=5),
        ),
    ]
