# Generated by Django 3.0.10 on 2020-11-07 22:27

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0023_auto_20201011_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='corporatevaluation.Project'),
        ),
    ]
