# Generated by Django 3.0.10 on 2021-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0024_auto_20201108_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='interest_coverage_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
