# Generated by Django 3.0.10 on 2021-07-15 07:41

import academycity.apps.core.sql
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporatevaluation', '0025_companydata_interest_coverage_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.CompanyInfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valuation',
                'verbose_name_plural': 'Valuations',
                'ordering': ['user', 'company_info'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
