# Generated by Django 3.0.10 on 2021-07-25 06:23

import academycity.apps.core.sql
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporatevaluation', '0026_valuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_todolists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'todolist',
                'verbose_name_plural': 'todolist',
                'ordering': ['-priority'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
