# Generated by Django 3.0.10 on 2021-08-05 03:45

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0028_auto_20210728_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLMainIndustryInfo',
            fields=[
                ('sic_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'XBRLMainIndustry',
                'verbose_name_plural': 'XBRLMainIndustries',
                'ordering': ['sic_code'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLIndustryInfo',
            fields=[
                ('sic_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('main_sic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLMainIndustryInfo')),
            ],
            options={
                'verbose_name': 'XBRLIndustry',
                'verbose_name_plural': 'XBRLIndustries',
                'ordering': ['sic_code'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
