# Generated by Django 3.0.10 on 2021-08-12 14:08

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0030_xbrlcompanyinfoinprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLValuationAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'XBRLValuationAccount',
                'verbose_name_plural': 'XBRLValuationAccounts',
                'ordering': ['order'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='xbrlcompanyinfoinprocess',
            options={'ordering': ['company_name'], 'verbose_name': 'XBRLCompanyInfoInProcess', 'verbose_name_plural': 'XBRLCompanyInfoInProcesses'},
        ),
    ]
