# Generated by Django 3.0.10 on 2021-08-13 06:58

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0031_auto_20210812_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='nyse', max_length=10)),
                ('company_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('ticker', models.CharField(max_length=10)),
                ('company_letter', models.CharField(default='', max_length=1)),
                ('cik', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLIndustryInfo')),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
                'ordering': ['company_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLValuationAccountsMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('match_account', models.CharField(max_length=250, null=True)),
                ('accounting_standard', models.CharField(default='us-gaap', max_length=250)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLValuationAccounts')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLCompanyInfo')),
            ],
            options={
                'verbose_name': 'XBRLValuationAccount',
                'verbose_name_plural': 'XBRLValuationAccounts',
                'ordering': ['company', 'account'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
