# Generated by Django 3.0.10 on 2021-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0032_xbrlcompanyinfo_xbrlvaluationaccountsmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlcompanyinfo',
            options={'ordering': ['company_name'], 'verbose_name': 'XBRL Company Info', 'verbose_name_plural': 'XBRL Companies Info'},
        ),
        migrations.AlterModelOptions(
            name='xbrlvaluationaccountsmatch',
            options={'ordering': ['company', 'account'], 'verbose_name': 'XBRLValuationAccountMatch', 'verbose_name_plural': 'XBRLValuationAccountsMatch'},
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='state',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='zip',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
