# Generated by Django 3.0.10 on 2021-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0033_auto_20210813_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlvaluationaccounts',
            name='type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
