# Generated by Django 3.0.10 on 2021-08-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0034_xbrlvaluationaccounts_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['sic_code'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industry'},
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfoinprocess',
            name='cik',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfoinprocess',
            name='sic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
