# Generated by Django 3.0.10 on 2021-08-31 18:29

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0035_auto_20210821_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('iso_2', models.BooleanField(default=0)),
                ('iso_3', models.BooleanField(default=0)),
                ('oecd', models.BooleanField(default=0)),
                ('eu27', models.BooleanField(default=0)),
                ('gseven', models.BooleanField(default=0)),
                ('gtwenty', models.BooleanField(default=0)),
                ('brics', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'XBRL Country',
                'verbose_name_plural': 'XBRL Countries',
                'ordering': ['name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'XBRL Region',
                'verbose_name_plural': 'XBRL Regions',
                'ordering': ['name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='xbrlindustryinfo',
            options={'ordering': ['sic_description'], 'verbose_name': 'XBRLIndustry', 'verbose_name_plural': 'XBRLIndustries'},
        ),
        migrations.AlterField(
            model_name='xbrlvaluationaccountsmatch',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xbrl_valuation_accounts_match', to='corporatevaluation.XBRLCompanyInfo'),
        ),
        migrations.CreateModel(
            name='XBRLCountryYearData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gdp', models.DecimalField(decimal_places=5, max_digits=12)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLCountry')),
            ],
            options={
                'verbose_name': 'XBRL Country Yea rData',
                'verbose_name_plural': 'XBRL Countries Year Data',
                'ordering': ['country', 'year'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='xbrlcountry',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.XBRLRegion'),
        ),
    ]
