# Generated by Django 3.0.10 on 2021-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0036_auto_20210831_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlcountry',
            name='iso_2',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='xbrlcountry',
            name='iso_3',
            field=models.CharField(default='', max_length=3),
        ),
    ]
