# Generated by Django 3.0.10 on 2021-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0037_auto_20210831_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlcountryyeardata',
            name='gdp',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlcountryyeardata',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
