# Generated by Django 3.0.10 on 2021-09-02 12:29

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0038_auto_20210831_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLValuationStatementsAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('statement', models.CharField(default='Income Statement', max_length=250)),
            ],
            options={
                'verbose_name': 'XBRLValuationStatementsAccount',
                'verbose_name_plural': 'XBRLValuationStatementsAccounts',
                'ordering': ['statement', 'order'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='xbrlvaluationaccounts',
            name='statement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xbrl_valuation_statements', to='corporatevaluation.XBRLValuationStatementsAccounts'),
        ),
    ]
