# Generated by Django 3.0.10 on 2021-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0039_auto_20210902_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlvaluationstatementsaccounts',
            options={'ordering': ['order'], 'verbose_name': 'XBRLValuationStatementsAccount', 'verbose_name_plural': 'XBRLValuationStatementsAccounts'},
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
