# Generated by Django 3.0.10 on 2021-09-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0040_auto_20210904_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='zip',
            field=models.CharField(default='', max_length=10),
        ),
    ]
