# Generated by Django 3.0.10 on 2021-09-04 19:15

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0041_auto_20210904_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLHistoricalReturnsSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('aaa', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('bbb', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('tb3ms', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('tb10y', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('sp500', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('Return_on_real_estate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
                ('home_prices', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8)),
                ('cpi', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8)),
            ],
            options={
                'verbose_name': 'XBRLHistoricalReturnsSP',
                'verbose_name_plural': 'XBRLHistoricalReturnsSP',
                'ordering': ['year'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
