# Generated by Django 3.0.10 on 2021-09-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0042_auto_20210904_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xbrlhistoricalreturnssp',
            old_name='Return_on_real_estate',
            new_name='return_on_real_estate',
        ),
    ]
