# Generated by Django 3.0.10 on 2021-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0043_auto_20210904_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='aaa',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='bbb',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='home_prices',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='return_on_real_estate',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='sp500',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='tb10y',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlhistoricalreturnssp',
            name='tb3ms',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
    ]
