# Generated by Django 3.0.10 on 2021-09-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0044_auto_20210904_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlhistoricalreturnssp',
            options={'ordering': ['-year'], 'verbose_name': 'XBRLHistoricalReturnsSP', 'verbose_name_plural': 'XBRLHistoricalReturnsSP'},
        ),
        migrations.AddField(
            model_name='xbrlhistoricalreturnssp',
            name='risk_premium',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=8, null=True),
        ),
    ]
