# Generated by Django 3.0.10 on 2021-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0045_auto_20210905_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlvaluationaccounts',
            name='scale',
            field=models.PositiveIntegerField(default=1000000),
        ),
    ]
