# Generated by Django 3.0.10 on 2021-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0047_xbrlregion_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcountry',
            name='updated_adamodar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xbrlregion',
            name='updated_adamodar',
            field=models.BooleanField(default=False),
        ),
    ]
