# Generated by Django 3.0.10 on 2021-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0048_auto_20210910_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcountryyeardata',
            name='CDS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='xbrlcountryyeardata',
            name='composite_risk_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='xbrlcountryyeardata',
            name='moodys_rating',
            field=models.CharField(default='Income Statement', max_length=20),
        ),
        migrations.AddField(
            model_name='xbrlcountryyeardata',
            name='sp_rating',
            field=models.CharField(default='Income Statement', max_length=250),
        ),
    ]
