# Generated by Django 3.0.10 on 2021-09-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0049_auto_20210910_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xbrlcountryyeardata',
            old_name='CDS',
            new_name='cds',
        ),
        migrations.AlterField(
            model_name='xbrlcountryyeardata',
            name='moodys_rating',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='xbrlcountryyeardata',
            name='sp_rating',
            field=models.CharField(default='', max_length=250),
        ),
    ]
