# Generated by Django 3.0.10 on 2021-09-12 09:22

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0050_auto_20210911_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLSPMoodys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('sp', models.CharField(default='Income Statement', max_length=10)),
                ('moodys', models.CharField(default='Income Statement', max_length=10)),
            ],
            options={
                'verbose_name': 'XBRLHistoricalReturnsSP',
                'verbose_name_plural': 'XBRLHistoricalReturnsSP',
                'ordering': ['-year'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
