# Generated by Django 3.0.10 on 2021-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0051_xbrlspmoodys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlspmoodys',
            options={'ordering': ['-year'], 'verbose_name': 'XBRLSPMoodys', 'verbose_name_plural': 'XBRLSPMoodys'},
        ),
        migrations.AddField(
            model_name='xbrlspmoodys',
            name='default_spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
