# Generated by Django 3.0.10 on 2021-09-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0052_auto_20210912_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspmoodys',
            name='score_from',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspmoodys',
            name='score_to',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspmoodys',
            name='moodys',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='xbrlspmoodys',
            name='sp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
