# Generated by Django 3.0.10 on 2021-09-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0053_auto_20210919_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quarter',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='xbrlcountry',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='corporatevaluation.XBRLRegion'),
        ),
        migrations.AlterField(
            model_name='xbrlcountryyeardata',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_data', to='corporatevaluation.XBRLCountry'),
        ),
    ]
