# Generated by Django 3.1.13 on 2021-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0054_auto_20210924_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='financial_data',
            field=models.JSONField(null=True),
        ),
    ]
