# Generated by Django 3.1.13 on 2021-10-05 18:47

import academycity.apps.core.sql
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporatevaluation', '0056_project_dic_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLSPEarningForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'XBRLSPEarningForcast',
                'verbose_name_plural': 'XBRLSPEarningForcast',
                'ordering': ['-created'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='xbrlvaluationaccountsmatch',
            options={'ordering': ['company'], 'verbose_name': 'XBRLValuationAccountMatch', 'verbose_name_plural': 'XBRLValuationAccountsMatch'},
        ),
        migrations.CreateModel(
            name='XBRLValuationCompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='valuation_analysis_user', to='cms.placeholder')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_companies', to='corporatevaluation.xbrlcompanyinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XBRL Company Info',
                'verbose_name_plural': 'XBRL Companies Info',
                'ordering': ['company', 'user'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
