# Generated by Django 3.1.13 on 2021-10-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0057_auto_20211005_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_forecast', to='corporatevaluation.companyinfo'),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2021),
        ),
    ]
