# Generated by Django 3.1.13 on 2021-10-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0058_auto_20211005_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_forecast', to='corporatevaluation.xbrlcompanyinfo'),
        ),
    ]
