# Generated by Django 3.1.13 on 2021-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0059_auto_20211006_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='today_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='yesterday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='forecast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
