# Generated by Django 3.1.13 on 2021-10-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0060_auto_20211006_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlspearningforecast',
            options={'ordering': ['-date'], 'verbose_name': 'XBRLSPEarningForcast', 'verbose_name_plural': 'XBRLSPEarningForcast'},
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='next_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
