# Generated by Django 3.1.13 on 2021-10-26 12:37

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0061_auto_20211012_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLDimAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_order', models.PositiveSmallIntegerField(default=0)),
                ('statement', models.CharField(default='Income Statement', max_length=250)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.CharField(max_length=250, null=True)),
                ('parent', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'XBRL Dim Account',
                'verbose_name_plural': 'XBRL Dim Account',
                'ordering': ['statement_order', 'order'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLDimCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_sic_code', models.PositiveSmallIntegerField()),
                ('main_sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('sic_code', models.PositiveSmallIntegerField()),
                ('sic_description', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('exchange', models.CharField(default='nyse', max_length=10)),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'XBRL Dim Company Info',
                'verbose_name_plural': 'XBRL Dim Companies Info',
                'ordering': ['main_sic_code', 'sic_code', 'company_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLDimTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('quarter', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'XBRL Dim Time',
                'verbose_name_plural': 'XBRL Dim Time',
                'ordering': ['year', 'quarter'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='xbrlspearningforecast',
            options={'ordering': ['next_release_date'], 'verbose_name': 'XBRLSPEarningForcast', 'verbose_name_plural': 'XBRLSPEarningForcast'},
        ),
        migrations.CreateModel(
            name='XBRLSPStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_release_date', models.DateField(blank=True, null=True)),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_statistic', to='corporatevaluation.xbrlcompanyinfo')),
            ],
            options={
                'verbose_name': 'XBRLSPStatistic',
                'verbose_name_plural': 'XBRLSPStatistics',
                'ordering': ['next_release_date'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLFactCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_companies', to='corporatevaluation.xbrldimaccount')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_companies', to='corporatevaluation.xbrldimcompany')),
                ('time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_times', to='corporatevaluation.xbrldimtime')),
            ],
            options={
                'verbose_name': 'XBRL Fact',
                'verbose_name_plural': 'XBRL Facts',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
