# Generated by Django 3.1.13 on 2021-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0063_xbrlspstatistics_mean_abs_price_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='correlation_afp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='mean_abs_actual_forecast_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
