# Generated by Django 3.1.13 on 2021-10-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0064_auto_20211027_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspstatistics',
            name='updated',
            field=models.DateField(),
        ),
    ]
