# Generated by Django 3.1.13 on 2021-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0065_auto_20211028_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlvaluationaccounts',
            name='sic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
