# Generated by Django 3.1.13 on 2021-10-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0066_xbrlvaluationaccounts_sic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspstatistics',
            name='correlation_afp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspstatistics',
            name='mean_abs_actual_forecast_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspstatistics',
            name='mean_abs_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
