# Generated by Django 3.1.13 on 2021-11-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0067_auto_20211031_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='butterfly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='straddle_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
