# Generated by Django 3.1.13 on 2021-11-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0068_auto_20211106_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='announcement_time',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
