# Generated by Django 3.1.13 on 2021-11-11 17:27

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0069_xbrlspstatistics_announcement_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='by_country_or_regine',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='XBRLRegionsOfOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions_of_operation', to='corporatevaluation.xbrlcompanyinfo')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies_by_region', to='corporatevaluation.xbrlregion')),
            ],
            options={
                'verbose_name': 'XBRL region Of Operations',
                'verbose_name_plural': 'XBRL regions Of Operations',
                'ordering': ['region'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLCountriesOfOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries_of_operation', to='corporatevaluation.xbrlcompanyinfo')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies_by_country', to='corporatevaluation.xbrlcountry')),
            ],
            options={
                'verbose_name': 'XBRL Country Of Operations',
                'verbose_name_plural': 'XBRL Countries Of Operations',
                'ordering': ['country'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
