# Generated by Django 3.1.13 on 2021-11-13 19:40

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0070_auto_20211111_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xbrlcountriesofoperations',
            name='company',
        ),
        migrations.RemoveField(
            model_name='xbrlregionsofoperations',
            name='company',
        ),
        migrations.AlterField(
            model_name='xbrlcountriesofoperations',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_year_countries', to='corporatevaluation.xbrlcountry'),
        ),
        migrations.AlterField(
            model_name='xbrlregionsofoperations',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_year_regions', to='corporatevaluation.xbrlregion'),
        ),
        migrations.CreateModel(
            name='XBRLYearsCompanyOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2020)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years_of_operation', to='corporatevaluation.xbrlcompanyinfo')),
            ],
            options={
                'verbose_name': 'XBRL Year Company Of Operations',
                'verbose_name_plural': 'XBRL Year companies Of Operations',
                'ordering': ['year'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='xbrlcountriesofoperations',
            name='company_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries_of_operation', to='corporatevaluation.xbrlyearscompanyoperations'),
        ),
        migrations.AddField(
            model_name='xbrlregionsofoperations',
            name='company_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions_of_operation', to='corporatevaluation.xbrlyearscompanyoperations'),
        ),
    ]
