# Generated by Django 3.1.13 on 2021-11-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0071_auto_20211113_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years_companies_of_operation', to='corporatevaluation.xbrlcountry'),
        ),
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='revenues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='risk_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlyearscompanyoperations',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
