# Generated by Django 3.1.13 on 2021-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0072_auto_20211115_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='country',
        ),
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='revenues',
        ),
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='risk_premium',
        ),
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='xbrlyearscompanyoperations',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='xbrlcountriesofoperations',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='xbrlcountriesofoperations',
            name='risk_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlcountriesofoperations',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='xbrlcountriesofoperations',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
