# Generated by Django 3.1.13 on 2021-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0074_auto_20211115_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlregionyeardata',
            name='moodys_rate_completed_by_sp',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
