# Generated by Django 3.1.13 on 2021-11-17 17:53

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0075_auto_20211116_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLIndustryBetasOfOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ev_over_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unlevered_beta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industries_of_operation', to='corporatevaluation.xbrlyearscompanyoperations')),
                ('industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_year_industries', to='corporatevaluation.globalindustryaverages')),
            ],
            options={
                'verbose_name': 'XBRL industry beta Of Operations',
                'verbose_name_plural': 'XBRL industry betas Of Operations',
                'ordering': ['industry'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
