# Generated by Django 3.1.13 on 2021-11-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0076_xbrlindustrybetasofoperations'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='country_of_incorporation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_companies', to='corporatevaluation.xbrlcountry'),
        ),
    ]
