# Generated by Django 3.1.13 on 2021-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0077_xbrlcompanyinfo_country_of_incorporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='financial_dataq',
            field=models.JSONField(null=True),
        ),
    ]
