# Generated by Django 3.1.13 on 2021-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0078_xbrlcompanyinfo_financial_dataq'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspstatistics',
            name='mean_abs_actual_forecast_change_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
