# Generated by Django 3.1.13 on 2021-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0081_auto_20211209_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xbrldimaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='xbrldimaccount',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xbrldimcompany',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xbrldimtime',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
