# Generated by Django 3.1.13 on 2021-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0082_auto_20211209_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlfactcompany',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
