# Generated by Django 3.1.13 on 2022-01-13 08:47

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0084_auto_20220111_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLRealEquityPricesArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('t', models.PositiveBigIntegerField(default=0)),
                ('o', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('v', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'XBRLRealEquityPricesArchive',
                'verbose_name_plural': 'XBRLRealEquityPricesArchive',
                'ordering': ['ticker'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
