# Generated by Django 3.1.13 on 2022-02-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0085_xbrlrealequitypricesarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspstatistics',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
