# Generated by Django 3.1.13 on 2022-06-20 18:38

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0089_corporatevaluationweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETF',
                'ordering': ['symbol'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompaniesETFData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.xbrlcompanyinfo')),
                ('etf', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.etf')),
            ],
            options={
                'verbose_name': 'CompaniesETFData',
                'verbose_name_plural': 'CompaniesETFData',
                'ordering': ['etf'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
