# Generated by Django 3.1.13 on 2022-06-22 09:42

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0090_companiesetfdata_etf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'CompaniesData',
                'verbose_name_plural': 'CompaniesData',
                'ordering': ['company'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='etf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.etf'),
        ),
        migrations.DeleteModel(
            name='CompaniesETFData',
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporatevaluation.xbrlcompanyinfo'),
        ),
    ]
