# Generated by Django 3.1.13 on 2022-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0091_auto_20220622_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompaniesData',
            new_name='CompaniesPriceData',
        ),
    ]
