# Generated by Django 3.1.13 on 2022-06-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0092_auto_20220622_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companiespricedata',
            options={'ordering': ['company'], 'verbose_name': 'CompaniesPriceData', 'verbose_name_plural': 'CompaniesPriceData'},
        ),
    ]
