# Generated by Django 3.1.13 on 2022-06-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0093_auto_20220622_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETF',
            new_name='ETFS',
        ),
    ]
