# Generated by Django 3.1.13 on 2022-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0094_auto_20220622_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
    ]
