# Generated by Django 3.1.13 on 2022-08-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0095_auto_20220716_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etfs',
            options={'ordering': ['symbol'], 'verbose_name': 'ETFS', 'verbose_name_plural': 'ETFS'},
        ),
    ]
