# Generated by Django 3.1.13 on 2022-10-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0096_auto_20220808_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=4),
        ),
    ]
