# Generated by Django 3.1.13 on 2022-10-12 11:14

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0097_auto_20221010_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'ETFS',
                'verbose_name_plural': 'ETFS',
                'ordering': ['symbol'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='xbrlcompanyinfo',
            name='etf',
        ),
    ]
