# Generated by Django 3.1.13 on 2022-10-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0098_auto_20221012_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='etf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eft_xbrlcompanyinfo', to='corporatevaluation.etfs'),
        ),
    ]
