# Generated by Django 3.1.13 on 2022-10-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0099_xbrlcompanyinfo_etf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='ETFWatchList',
        ),
        migrations.AlterModelOptions(
            name='etfwatchlist',
            options={'ordering': ['symbol'], 'verbose_name': 'ETFWatchList', 'verbose_name_plural': 'ETFWatchList'},
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='etf_watchlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etf_watch_list_xbrlcompanyinfo', to='corporatevaluation.etfs'),
        ),
    ]
