# Generated by Django 3.1.13 on 2022-10-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0100_auto_20221012_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlcompanyinfo',
            name='etf_watchlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etf_watch_list_xbrlcompanyinfo', to='corporatevaluation.etfwatchlist'),
        ),
    ]
