# Generated by Django 3.1.13 on 2022-10-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0101_auto_20221012_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETFWatchList',
            new_name='ETFWatchLists',
        ),
        migrations.RenameField(
            model_name='xbrlcompanyinfo',
            old_name='etf_watchlist',
            new_name='etfwatchlist',
        ),
    ]
