# Generated by Django 3.1.13 on 2022-10-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0102_auto_20221012_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etfwatchlists',
            options={'ordering': ['symbol'], 'verbose_name': 'ETFWatchLists', 'verbose_name_plural': 'ETFWatchLists'},
        ),
    ]
