# Generated by Django 3.1.13 on 2022-10-17 02:27

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0103_auto_20221012_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('idx', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('dividends', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_splits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
