# Generated by Django 3.1.13 on 2022-10-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0105_stockprices_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockPrices',
            new_name='StockPricesMinutes',
        ),
    ]
