# Generated by Django 3.1.13 on 2022-10-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0106_auto_20221017_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPricesMinutes',
        ),
    ]
