# Generated by Django 3.1.13 on 2022-10-19 20:28

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0108_stockpricesminutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpricesminutes',
            options={'ordering': ['company__id', '-idx'], 'verbose_name': 'StockPricesMinute', 'verbose_name_plural': 'StockPricesMinutes'},
        ),
        migrations.CreateModel(
            name='StockPricesDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveBigIntegerField(default=0)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info_stock_prices_days', to='corporatevaluation.xbrlcompanyinfo')),
            ],
            options={
                'verbose_name': 'StockPricesDay',
                'verbose_name_plural': 'StockPricesDays',
                'ordering': ['company__id', '-idx'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
