# Generated by Django 3.1.13 on 2022-10-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0109_auto_20221019_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricesdays',
            name='dividends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockpricesdays',
            name='stock_splits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
