# Generated by Django 3.1.13 on 2023-04-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0111_auto_20230112_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=2),
        ),
    ]
