# Generated by Django 3.1.13 on 2023-06-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0113_auto_20230523_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlfactcompany',
            options={'verbose_name': 'XBRL Fact Company', 'verbose_name_plural': 'XBRL Fact Companies'},
        ),
    ]
