# Generated by Django 3.1.13 on 2023-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0114_auto_20230616_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-is_active', '-priority', 'description'], 'verbose_name': 'todolist', 'verbose_name_plural': 'todolist'},
        ),
    ]
