# Generated by Django 3.1.13 on 2023-06-29 11:32

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0116_xbrlfactratioscompany_xbrlprocessedfactcompany_xbrlratiodim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlprocessedfactcompany',
            options={'verbose_name': 'XBRL Processed Fact Company', 'verbose_name_plural': 'XBRL Processed Fact Companies'},
        ),
        migrations.AlterModelOptions(
            name='xbrlratiodim',
            options={'ordering': ['industry', 'ratio_group'], 'verbose_name': 'XBRL Ratio Dim', 'verbose_name_plural': 'XBRL Ratio Dims'},
        ),
        migrations.CreateModel(
            name='XBRLAccountsGroupsFactCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_accounts_groups_companies', to='corporatevaluation.xbrldimcompany')),
                ('time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_accounts_groups_times', to='corporatevaluation.xbrldimtime')),
            ],
            options={
                'verbose_name': 'XBRL Processed Fact Company',
                'verbose_name_plural': 'XBRL Processed Fact Companies',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
