# Generated by Django 3.1.13 on 2023-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0117_auto_20230629_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlaccountsgroupsfactcompany',
            options={'verbose_name': 'XBRL Accounts Groups Fact Company', 'verbose_name_plural': 'XBRL Accounts Groups Fact Companies'},
        ),
        migrations.AddField(
            model_name='xbrlcompanyinfo',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xbrlindustryinfo',
            name='industry_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=3),
        ),
    ]
