# Generated by Django 3.1.13 on 2023-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0118_auto_20230704_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=4),
        ),
    ]
