# Generated by Django 3.1.13 on 2023-12-17 18:02

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0120_twospreadstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoSpreadStrategyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveBigIntegerField(default=0)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('strategy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('two_spread_strategy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_spread_strategy_details', to='corporatevaluation.twospreadstrategy')),
            ],
            options={
                'verbose_name': 'TwoSpreadStrategyDetail',
                'verbose_name_plural': 'TwoSpreadStrategyDetails',
                'ordering': ['-idx'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
