# Generated by Django 3.1.13 on 2023-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0121_twospreadstrategydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='twospreadstrategydetails',
            name='seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
