# Generated by Django 3.1.13 on 2023-12-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0123_auto_20231222_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpricesminutes',
            options={'ordering': ['company__id', 'idx'], 'verbose_name': 'StockPricesMinute', 'verbose_name_plural': 'StockPricesMinutes'},
        ),
        migrations.AddField(
            model_name='twospreadstrategy',
            name='is_open_position',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twospreadstrategy',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
