# Generated by Django 3.1.13 on 2023-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0124_auto_20231223_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='twospreadstrategydetails',
            name='call_strategy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='twospreadstrategydetails',
            name='put_strategy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
