# Generated by Django 3.1.13 on 2023-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0125_auto_20231226_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='twospreadstrategy',
            name='call_strategy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='twospreadstrategy',
            name='put_strategy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='twospreadstrategy',
            name='strategy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
