# Generated by Django 3.1.13 on 2024-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0126_auto_20231228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2024),
        ),
    ]
