# Generated by Django 3.1.13 on 2024-03-12 20:11

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0127_auto_20240101_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=1)),
                ('spread', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inner_range', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ch', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('p', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ph', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_fact_simulation', to='corporatevaluation.xbrlcompanyinfo')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['stock_price'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
