# Generated by Django 3.1.13 on 2024-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0128_factsimulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factsimulation',
            options={'ordering': ['time', 'stock_price'], 'verbose_name': 'FactSimulation', 'verbose_name_plural': 'FactSimulations'},
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=2),
        ),
    ]
