# Generated by Django 3.1.13 on 2024-12-20 11:01

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0131_auto_20241113_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='XBRLVarDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_order', models.PositiveSmallIntegerField(default=0)),
                ('var_name', models.CharField(max_length=250, null=True)),
                ('source', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'XBRL Var Dim',
                'verbose_name_plural': 'XBRL Var Dims',
                'ordering': ['var_order'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='XBRLFactVarsCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_fact_var_companies', to='corporatevaluation.xbrldimcompany')),
                ('time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_fact_var_times', to='corporatevaluation.xbrldimtime')),
                ('var', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dim_fact_var_ratio', to='corporatevaluation.xbrlvardim')),
            ],
            options={
                'verbose_name': 'XBRL Fact Ratios Company',
                'verbose_name_plural': 'XBRL Fact Ratios Companies',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
