# Generated by Django 3.1.13 on 2024-12-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0132_xbrlfactvarscompany_xbrlvardim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlratiodim',
            options={'ordering': ['industry', 'ratio_order'], 'verbose_name': 'XBRL Ratio Dim', 'verbose_name_plural': 'XBRL Ratio Dims'},
        ),
        migrations.RenameField(
            model_name='xbrlratiodim',
            old_name='ratio_group',
            new_name='ratio_order',
        ),
    ]
