# Generated by Django 3.1.13 on 2025-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0133_auto_20241220_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xbrlfactvarscompany',
            options={'verbose_name': 'XBRL Fact Var Company', 'verbose_name_plural': 'XBRL Fact Vars Companies'},
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='market_cap',
            field=models.BigIntegerField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='revenue_actual',
            field=models.BigIntegerField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='revenue_forecast',
            field=models.BigIntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2025),
        ),
    ]
