# Generated by Django 3.1.13 on 2025-04-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatevaluation', '0134_auto_20250430_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbrlspearningforecast',
            name='release_time',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='revenue_actual',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xbrlspearningforecast',
            name='revenue_forecast',
            field=models.BigIntegerField(default=0),
        ),
    ]
