# Generated by Django 3.0.10 on 2021-03-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ueconomics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source',
        ),
        migrations.AddField(
            model_name='yeardata',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_year_data', to='ueconomics.Source'),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_year_data', to='ueconomics.Product'),
        ),
    ]
