# Generated by Django 3.1.13 on 2024-04-16 14:38

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FoodDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('food_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_dim_group_dim', to='nu.foodgroupdim')),
            ],
            options={
                'verbose_name': 'fooddim',
                'verbose_name_plural': 'fooddims',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
