# Generated by Django 3.1.13 on 2024-04-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddim',
            old_name='food_group_dim',
            new_name='group_name',
        ),
    ]
