# Generated by Django 3.1.13 on 2024-04-26 13:54

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nu', '0002_auto_20240419_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitamin_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'vitamindim',
                'verbose_name_plural': 'vitamindims',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VitaminFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('food_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_dim_fact', to='nu.fooddim')),
                ('vitamin_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vitamin_dim_fact', to='nu.vitamindim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
