# Generated by Django 3.1.13 on 2022-11-27 12:48

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battalions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battalion_name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('battalion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battalion_companys', to='training.battalions')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_sections', to='training.companys')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='trainingweb',
            name='max_participants_in_team',
        ),
        migrations.RemoveField(
            model_name='trainingweb',
            name='number_of_participants',
        ),
        migrations.RemoveField(
            model_name='trainingweb',
            name='number_of_periods',
        ),
        migrations.RemoveField(
            model_name='trainingweb',
            name='number_of_teams',
        ),
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='section_squads', to='training.sections')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_squads', to='training.trainingweb')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Soldiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rank', models.SmallIntegerField(default=0)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('blood_type', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('marital_status', models.SmallIntegerField(default=0)),
                ('num_of_children', models.SmallIntegerField(default=0)),
                ('shirt_size', models.SmallIntegerField(default=0)),
                ('pant_size', models.SmallIntegerField(default=0)),
                ('shoes_size', models.SmallIntegerField(default=0)),
                ('height', models.SmallIntegerField(default=0)),
                ('weight', models.SmallIntegerField(default=0)),
                ('medical_condition', models.TextField()),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squad_soldiers', to='training.squads')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_soldiers', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'soldier',
                'verbose_name_plural': 'soldiers',
                'ordering': ['last_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sections',
            name='training_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_sections', to='training.trainingweb'),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_officers', to='training.trainingweb')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='companys',
            name='training_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_companys', to='training.trainingweb'),
        ),
        migrations.CreateModel(
            name='Brigades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_brigades', to='training.trainingweb')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='battalions',
            name='brigade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brigade_battalions', to='training.brigades'),
        ),
        migrations.AddField(
            model_name='battalions',
            name='training_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_battalions', to='training.trainingweb'),
        ),
    ]
