# Generated by Django 3.1.13 on 2022-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20221127_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiers',
            name='medical_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
