# Generated by Django 3.1.13 on 2022-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20221127_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='discipline',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='profession',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='strength',
            field=models.SmallIntegerField(default=0),
        ),
    ]
