# Generated by Django 3.1.13 on 2022-11-29 14:47

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20221128_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.SmallIntegerField(default=0)),
                ('test', models.SmallIntegerField(default=0)),
                ('value', models.SmallIntegerField(default=0)),
                ('soldier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_private_specialties', to='training.squads')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_private_specialties', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'private_speciality',
                'verbose_name_plural': 'private_specialities',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
