# Generated by Django 3.1.13 on 2022-11-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_privatespecialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatespecialty',
            name='soldier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_private_specialties', to='training.soldiers'),
        ),
    ]
