# Generated by Django 3.1.13 on 2022-11-30 14:18

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20221129_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleShoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_shoot_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('soldier', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_double_shoot', to='training.soldiers')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
