# Generated by Django 3.1.13 on 2022-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_doubleshoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleshoot',
            name='is_pulled',
            field=models.BooleanField(default=False),
        ),
    ]
