# Generated by Django 3.1.13 on 2022-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_doubleshoot_is_pulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatespecialty',
            name='obj_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
