# Generated by Django 3.1.13 on 2023-01-12 15:28

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_privatespecialty_obj_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test', models.SmallIntegerField(default=0)),
                ('value', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'soldier_fact',
                'verbose_name_plural': 'soldier_facts',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimeDim',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('month', models.PositiveSmallIntegerField(default=0)),
                ('day', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='sub_profession',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PrivateSpecialty',
        ),
        migrations.AddField(
            model_name='soldierfact',
            name='soldier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_soldier_facts', to='training.soldiers'),
        ),
        migrations.AddField(
            model_name='soldierfact',
            name='time_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_soldier_facts', to='training.timedim'),
        ),
        migrations.AddField(
            model_name='soldierfact',
            name='training_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_soldier_facts', to='training.trainingweb'),
        ),
    ]
