# Generated by Django 3.1.13 on 2023-01-20 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0011_auto_20230120_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldiers',
            name='id',
        ),
        migrations.AddField(
            model_name='soldiers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldiers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_training', serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
