# Generated by Django 3.1.13 on 2023-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20230122_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platoons',
            options={'ordering': ['company', 'platoon_number'], 'verbose_name': 'platoon', 'verbose_name_plural': 'platoons'},
        ),
        migrations.AlterModelOptions(
            name='squads',
            options={'ordering': ['platoon', 'squad_name'], 'verbose_name': 'squad', 'verbose_name_plural': 'squads'},
        ),
        migrations.RemoveField(
            model_name='compliances',
            name='file',
        ),
        migrations.AddField(
            model_name='instructors',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
