# Generated by Django 3.1.13 on 2023-01-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20230124_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='squads',
            name='squad_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
