# Generated by Django 3.1.13 on 2023-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_squads_squad_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalions',
            name='battalion_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
