# Generated by Django 3.1.13 on 2023-01-31 08:40

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('training', '0018_compliances_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='training_user_test_events', serialize=False, to='auth.user')),
                ('test_event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_test_events', to='training.timedim')),
            ],
            options={
                'verbose_name': 'test_event',
                'verbose_name_plural': 'test_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
