# Generated by Django 3.1.13 on 2023-01-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_testevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsstructures',
            options={'verbose_name': 'test_structure', 'verbose_name_plural': 'test_structures'},
        ),
    ]
