# Generated by Django 3.1.13 on 2023-01-31 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0020_auto_20230131_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestEvent',
            new_name='TestEvents',
        ),
    ]
