# Generated by Django 3.1.13 on 2023-01-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20230131_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestEvents',
        ),
    ]
