# Generated by Django 3.1.13 on 2023-01-31 14:28

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_delete_testevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_event_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('instructor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_instructor_test_events', to='training.instructors')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_test_events', to='training.timedim')),
            ],
            options={
                'verbose_name': 'test_event',
                'verbose_name_plural': 'test_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
