# Generated by Django 3.1.13 on 2023-02-01 07:51

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_testevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsForEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveSmallIntegerField(default=0)),
                ('testevent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_event_tests_for_events', to='training.testevents')),
            ],
            options={
                'verbose_name': 'test_event',
                'verbose_name_plural': 'test_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
