# Generated by Django 3.1.13 on 2023-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20230201_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiers',
            name='sport_size',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='uniform_size',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
