# Generated by Django 3.1.13 on 2023-02-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20230201_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsforevents',
            options={'verbose_name': 'test_for_event', 'verbose_name_plural': 'test_for_events'},
        ),
        migrations.AddField(
            model_name='testsforevents',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
