# Generated by Django 3.1.13 on 2023-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20230202_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsforevents',
            name='test_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
