# Generated by Django 3.1.13 on 2023-02-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20230202_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companys',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companys'},
        ),
    ]
