# Generated by Django 3.1.13 on 2023-02-03 12:25

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_auto_20230202_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldiersForEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier_number', models.PositiveIntegerField(default=0)),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('testevent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_event_soldiers_for_events', to='training.testevents')),
            ],
            options={
                'verbose_name': 'soldiers_for_event',
                'verbose_name_plural': 'soldiers_for_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
