# Generated by Django 3.1.13 on 2023-02-04 20:45

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_soldiersforevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesForEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier_number', models.PositiveIntegerField(default=0)),
                ('test_number', models.PositiveIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('testevent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_event_grades_for_events', to='training.testevents')),
            ],
            options={
                'verbose_name': 'grades_for_event',
                'verbose_name_plural': 'grades_for_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
