# Generated by Django 3.1.13 on 2023-02-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_gradesforevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesforevents',
            name='soldier_number',
        ),
        migrations.RemoveField(
            model_name='gradesforevents',
            name='test_number',
        ),
        migrations.AddField(
            model_name='gradesforevents',
            name='soldiersforevent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldiersforevent_grades_for_events', to='training.soldiersforevents'),
        ),
        migrations.AddField(
            model_name='gradesforevents',
            name='testsforevent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testsforevent_grades_for_events', to='training.testsforevents'),
        ),
    ]
