# Generated by Django 3.1.13 on 2023-02-06 05:26

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_auto_20230205_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_inventory_categorys', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventorys',
                'ordering': ['category_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Inventorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('inventorycategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_category_inventorys', to='training.inventorycategorys')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_inventories', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventorys',
                'ordering': ['inventory_number'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
