# Generated by Django 3.1.13 on 2023-02-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_inventorycategorys_inventorys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategorys',
            options={'ordering': ['category_name'], 'verbose_name': 'inventorycategory', 'verbose_name_plural': 'inventorycategorys'},
        ),
        migrations.AddField(
            model_name='soldiers',
            name='gun_mz4psn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_mz4psn_soldiers', to='training.inventorys'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='gun_ramonsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ramonsn_soldiers', to='training.inventorys'),
        ),
    ]
