# Generated by Django 3.1.13 on 2023-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_auto_20230206_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevents',
            name='units_description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
