# Generated by Django 3.1.13 on 2023-02-13 09:43

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_testevents_units_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('variable_description', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'test_event',
                'verbose_name_plural': 'test_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestsForVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('testsvariable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_variables_tests_for_variables', to='training.testsvariables')),
            ],
            options={
                'verbose_name': 'test_for_event',
                'verbose_name_plural': 'test_for_events',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
