# Generated by Django 3.1.13 on 2023-02-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0036_testsforvariables_testsvariables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsforvariables',
            options={'verbose_name': 'test_for_variable', 'verbose_name_plural': 'test_for_variables'},
        ),
        migrations.AlterModelOptions(
            name='testsvariables',
            options={'verbose_name': 'test_variable', 'verbose_name_plural': 'test_variables'},
        ),
    ]
