# Generated by Django 3.1.13 on 2023-03-18 19:41

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_auto_20230216_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceWithPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('battalion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battalion_compliance_with_plans', to='training.battalions')),
            ],
            options={
                'verbose_name': 'compliance_with_plan',
                'verbose_name_plural': 'compliance_with_plans',
                'ordering': ['week'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComplianceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_compliance_days', to='training.companys')),
                ('compliance_with_plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_with_plan_compliance_days', to='training.compliancewithplans')),
                ('time_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_dim_compliance_day', to='training.timedim')),
            ],
            options={
                'verbose_name': 'compliance_day',
                'verbose_name_plural': 'compliance_days',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
