# Generated by Django 3.1.13 on 2023-03-25 01:18

import academycity.apps.core.sql
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_complianceday_compliancewithplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('data_json', models.JSONField(null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UniteSoldiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_soldiers_number', models.IntegerField(default=0)),
                ('weeks', models.CharField(blank=True, default='W1-5', max_length=10, null=True)),
                ('unit', models.IntegerField(default=0)),
                ('soldier', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'unite_soldier',
                'verbose_name_plural': 'unite_soldiers',
                'ordering': ['weeks', 'unit'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
