# Generated by Django 3.1.13 on 2023-03-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_generaldata_unitesoldiers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralData',
        ),
    ]
