# Generated by Django 3.1.13 on 2023-03-29 09:27

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0041_auto_20230327_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.SmallIntegerField(default=1)),
                ('period_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('structure', models.JSONField(null=True)),
                ('battalion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battalion_periods', to='training.battalions')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_periods', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'period',
                'ordering': ['battalion', 'period_number'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
