# Generated by Django 3.1.13 on 2023-03-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0044_auto_20230329_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategorys',
            options={'ordering': ['category_name', 'category_name_1'], 'verbose_name': 'inventorycategory', 'verbose_name_plural': 'inventorycategorys'},
        ),
        migrations.RenameField(
            model_name='inventorycategorys',
            old_name='category',
            new_name='category_name',
        ),
    ]
