# Generated by Django 3.1.13 on 2023-03-29 19:18

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0045_auto_20230329_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('section_number', models.SmallIntegerField(default=1)),
                ('platoon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platoon_sections', to='training.platoons')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_sections', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['platoon', 'section_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnitSoldiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(default=0)),
                ('soldier', models.IntegerField(default=0)),
                ('period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='period_unit_soldiers', to='training.periods')),
            ],
            options={
                'verbose_name': 'unit_soldier',
                'verbose_name_plural': 'unit_soldiers',
                'ordering': ['soldier', 'unit_number'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='UniteSoldiers',
        ),
    ]
