# Generated by Django 3.1.13 on 2023-03-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0046_auto_20230329_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsoldiers',
            name='soldier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_unit_soldiers', to='training.soldiers'),
        ),
    ]
