# Generated by Django 3.1.13 on 2023-03-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0047_auto_20230330_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='battalion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='platoon_soldiers', to='training.battalions'),
        ),
    ]
