# Generated by Django 3.1.13 on 2023-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0048_soldiers_battalion'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='uniqueid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
