# Generated by Django 3.1.13 on 2023-04-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0049_soldiers_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevents',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='period_test_events', to='training.periods'),
        ),
    ]
