# Generated by Django 3.1.13 on 2023-05-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0052_auto_20230515_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubleshootmembers',
            options={'ordering': ['ds_id'], 'verbose_name': 'double_shoot_member', 'verbose_name_plural': 'double_shoot_members'},
        ),
        migrations.AddField(
            model_name='doubleshootmembers',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
