# Generated by Django 3.1.13 on 2023-05-17 08:16

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0053_auto_20230516_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierQualificationFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.SmallIntegerField(default=0)),
                ('value', models.SmallIntegerField(default=0)),
                ('soldier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_soldier_qualification_facts', to='training.soldiers')),
                ('training_web', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_soldier_qualification_facts', to='training.trainingweb')),
            ],
            options={
                'verbose_name': 'soldier_qualification_fact',
                'verbose_name_plural': 'soldier_qualification_facts',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
