# Generated by Django 3.1.13 on 2023-05-24 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0055_inventoryfact_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-is_active', 'priority'], 'verbose_name': 'todolist', 'verbose_name_plural': 'todolist'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_user_todolists', to=settings.AUTH_USER_MODEL),
        ),
    ]
