# Generated by Django 3.1.13 on 2023-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0056_auto_20230524_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='default_battalion',
            field=models.IntegerField(default=1),
        ),
    ]
