# Generated by Django 3.1.13 on 2023-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0057_instructors_default_battalion'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalions',
            name='number_of_weeks',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='battalions',
            name='start_date',
            field=models.IntegerField(blank=True, default=230101, null=True),
        ),
    ]
