# Generated by Django 3.1.13 on 2023-05-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0059_battalions_number_of_weeks_in_period_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-is_active', 'priority', 'description'], 'verbose_name': 'todolist', 'verbose_name_plural': 'todolist'},
        ),
        migrations.AddField(
            model_name='complianceweeks',
            name='training_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_web_compliance_weeks', to='training.trainingweb'),
        ),
    ]
