# Generated by Django 3.1.13 on 2023-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0060_auto_20230528_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battalions',
            name='start_date',
            field=models.IntegerField(blank=True, default=20230101, null=True),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
