# Generated by Django 3.1.13 on 2023-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0063_auto_20230601_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryfact',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
