# Generated by Django 3.1.13 on 2023-06-1  11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0064_auto_20230602_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsforvariables',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
