# Generated by Django 3.1.13 on 2023-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0065_auto_20230612_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='s_first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='s_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
