# Generated by Django 3.1.13 on 2023-06-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0067_auto_20230618_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancedays',
            old_name='compliance_week',
            new_name='complianceweek',
        ),
    ]
