# Generated by Django 3.1.13 on 2023-06-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0068_auto_20230618_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdjectivesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, default=1)),
                ('value', models.CharField(max_length=50)),
                ('adjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.adjectives')),
            ],
        ),
    ]
