# Generated by Django 3.1.13 on 2023-09-03 21:39

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0072_inventorys_unit_critical'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnitFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.SmallIntegerField(default=0)),
                ('value', models.SmallIntegerField(default=0)),
                ('inventory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_unit_facts', to='training.inventorys')),
            ],
            options={
                'verbose_name': 'inventory_unit_fact',
                'verbose_name_plural': 'inventory_unit_facts',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
