# Generated by Django 3.1.13 on 2024-04-30 15:29

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Companies Info',
                'ordering': ['company_name'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockPricesDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveBigIntegerField(default=0)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('dividends', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_splits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info_stock_prices_days', to='op.companyinfo')),
            ],
            options={
                'verbose_name': 'StockPricesDay',
                'verbose_name_plural': 'StockPricesDays',
                'ordering': ['company__id', '-idx'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
