# Generated by Django 3.1.13 on 2024-05-10 07:27

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturnStd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveBigIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_stock_return_std', to='op.companyinfo')),
            ],
            options={
                'verbose_name': 'StockReturnStd',
                'verbose_name_plural': 'StockReturnStds',
                'ordering': ['company__id', '-idx'],
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
