# Generated by Django 3.1.13 on 2024-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_stockreturnstd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreturnstd',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
