# Generated by Django 3.1.13 on 2024-06-18 10:53

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_code', models.CharField(blank=True, default='', max_length=40, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, default=0, null=True)),
                ('dic_hp', models.JSONField(null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VarGroupDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VarDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_code', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('count0', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('count5', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('count10', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('count15', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('count20', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('var_group_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_dim_group_dim', to='case1.vargroupdim')),
            ],
            options={
                'verbose_name': 'vardim',
                'verbose_name_plural': 'vardims',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TempVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('temp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_vars', to='case1.temp')),
                ('var_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_dim_temp_var', to='case1.vardim')),
            ],
            options={
                'verbose_name': 'tempvar',
                'verbose_name_plural': 'tempvars',
            },
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='temp',
            name='dep_var_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dep_var_dim_temp_var', to='case1.vardim'),
        ),
        migrations.CreateModel(
            name='FactNormalizedMinMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('dep_var_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dep_var_dim_fact_normalized_minmax', to='case1.vardim')),
                ('entity_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_dim_fact_normalized_minmax', to='case1.entitydim')),
                ('var_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_dim_fact_normalized_minmax', to='case1.vardim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('entity_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_dim_fact', to='case1.entitydim')),
                ('var_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='var_dim_fact', to='case1.vardim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
