# Generated by Django 3.1.13 on 2022-05-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webcompanies', '0009_auto_20220210_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcompanies',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('accountingweb', 'fabhoseafricaweb', 'apewivesweb', 'radiusfoodweb', 'countries', 'institutionweb', 'checkcashingweb', 'portfolioweb')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webcompanies', to='contenttypes.contenttype'),
        ),
    ]
