# Generated by Django 3.1.13 on 2022-11-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webcompanies', '0015_auto_20221010_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcompanies',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('accountingweb', 'businesssimweb', 'acmathweb', 'dlweb', 'mlweb', 'corporatevaluationweb', 'macroeconomicweb', 'fabhoseafricaweb', 'apewivesweb', 'radiusfoodweb', 'countries', 'institutionweb', 'checkcashingweb', 'tradesweb', 'portfolioweb')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webcompanies', to='contenttypes.contenttype'),
        ),
    ]
