# Generated by Django 3.1.13 on 2022-12-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
