# Generated by Django 3.1.13 on 2022-12-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_auto_20221206_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedim',
            name='gene_code',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persondim',
            name='person_code',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
