# Generated by Django 3.1.13 on 2023-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0003_auto_20221209_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedim',
            name='clusters',
            field=models.JSONField(null=True),
        ),
    ]
