# Generated by Django 3.1.13 on 2023-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0004_genedim_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondim',
            name='age_at_cdna',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondim',
            name='gender',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='persondim',
            name='set_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
