# Generated by Django 3.1.13 on 2023-03-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0006_generaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='data_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
