# Generated by Django 3.1.13 on 2023-03-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0007_auto_20230325_0423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralData',
        ),
    ]
