# Generated by Django 3.1.13 on 2023-10-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0009_genedim_reduced_clusters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedim',
            options={'ordering': ['gene_code'], 'verbose_name': 'gendim', 'verbose_name_plural': 'gendims'},
        ),
    ]
