# Generated by Django 3.1.13 on 2024-01-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0012_genegroupdim'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedim',
            name='gene_group_dim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_dim_group_dim', to='ms.genegroupdim'),
        ),
    ]
