# Generated by Django 3.1.13 on 2024-01-17 13:02

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0015_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('sign', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('temp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_vars', to='ms.temp')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
