# Generated by Django 3.1.13 on 2024-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0016_tempvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedim',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
