# Generated by Django 3.1.13 on 2024-01-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0017_genedim_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedim',
            options={'ordering': ['-score'], 'verbose_name': 'gendim', 'verbose_name_plural': 'gendims'},
        ),
        migrations.AlterField(
            model_name='tempvar',
            name='var',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_dim_temp_var', to='ms.genedim'),
        ),
    ]
