# Generated by Django 3.1.13 on 2024-01-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0018_auto_20240118_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempvar',
            old_name='var',
            new_name='gene_dim',
        ),
    ]
