# Generated by Django 3.1.13 on 2024-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0019_auto_20240118_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedim',
            name='count0',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genedim',
            name='count10',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genedim',
            name='count15',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genedim',
            name='count20',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genedim',
            name='count5',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
