# Generated by Django 3.1.13 on 2024-01-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0020_auto_20240121_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempvar',
            options={'ordering': ['-amount'], 'verbose_name': 'tempvar', 'verbose_name_plural': 'tempvars'},
        ),
    ]
