# Generated by Django 3.1.13 on 2024-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0021_auto_20240122_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedim',
            options={'verbose_name': 'gendim', 'verbose_name_plural': 'gendims'},
        ),
        migrations.AlterModelOptions(
            name='tempvar',
            options={'verbose_name': 'tempvar', 'verbose_name_plural': 'tempvars'},
        ),
    ]
