# Generated by Django 3.1.13 on 2024-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0022_auto_20240123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedim',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
