# Generated by Django 3.1.13 on 2024-05-26 14:12

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0024_factnormalizedtemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.SmallIntegerField(blank=True, null=True)),
                ('sub_set', models.SmallIntegerField(blank=True, null=True)),
                ('component', models.SmallIntegerField(blank=True, null=True)),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PCAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('pca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pca_pca_data', to='ms.pca')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
