# Generated by Django 3.1.13 on 2024-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0025_pca_pcadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcadata',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
