# Generated by Django 3.1.13 on 2024-05-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0026_pcadata_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pca',
            options={'ordering': ['set', 'sub_set', 'component'], 'verbose_name': 'pca', 'verbose_name_plural': 'pcas'},
        ),
        migrations.AlterModelOptions(
            name='pcadata',
            options={'ordering': ['pca', 'idx'], 'verbose_name': 'pcadata', 'verbose_name_plural': 'pcadatas'},
        ),
    ]
