# Generated by Django 3.1.13 on 2024-07-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0029_temp_dep_var_dim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='dep_var_dim',
            new_name='dep_gene_dim',
        ),
    ]
