# Generated by Django 3.1.13 on 2024-07-31 10:38

import academycity.apps.core.sql
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0030_auto_20240730_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactNormalizedMinMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('dep_gene_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dep_gene_dim_fact_normalized_minmax', to='ms.genedim')),
                ('gene_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gene_dim_fact_normalized_minmax', to='ms.genedim')),
                ('person_dim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_dim_fact_normalized_minmax', to='ms.persondim')),
            ],
            bases=(academycity.apps.core.sql.TruncateTableMixin, models.Model),
        ),
    ]
