# Generated by Django 3.1.13 on 2024-09-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0032_auto_20240905_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='run_number',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
